/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.1.0.2506031608
    Soft IP Version: 1.0.0
    2025 12 04 09:59:11
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module emmc0 (rst_n_i, clk_i, emmc_clk_o, emmc_cmd_io, emmc_dat_io,
    emmc_rst_n_o, int_o, m_axi4_awready_i, m_axi4_awvalid_o, m_axi4_awid_o,
    m_axi4_awaddr_o, m_axi4_awlen_o, m_axi4_awsize_o, m_axi4_awburst_o,
    m_axi4_awprot_o, m_axi4_wready_i, m_axi4_wvalid_o, m_axi4_wdata_o,
    m_axi4_wstrb_o, m_axi4_wlast_o, m_axi4_bready_o, m_axi4_bvalid_i,
    m_axi4_bid_i, m_axi4_bresp_i, m_axi4_arready_i, m_axi4_arvalid_o,
    m_axi4_arid_o, m_axi4_araddr_o, m_axi4_arlen_o, m_axi4_arsize_o,
    m_axi4_arburst_o, m_axi4_arprot_o, m_axi4_rvalid_i, m_axi4_rready_o,
    m_axi4_rid_i, m_axi4_rdata_i, m_axi4_rresp_i, m_axi4_rlast_i,
    s_apb_penable_i, s_apb_psel_i, s_apb_pwrite_i, s_apb_paddr_i,
    s_apb_pwdata_i, s_apb_pready_o, s_apb_pslverr_o, s_apb_prdata_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  rst_n_i;
    input  clk_i;
    output  emmc_clk_o;
    inout  emmc_cmd_io;
    inout  [7:0]  emmc_dat_io;
    output  emmc_rst_n_o;
    output  int_o;
    input  m_axi4_awready_i;
    output  m_axi4_awvalid_o;
    output  [2:0]  m_axi4_awid_o;
    output  [31:0]  m_axi4_awaddr_o;
    output  [7:0]  m_axi4_awlen_o;
    output  [2:0]  m_axi4_awsize_o;
    output  [1:0]  m_axi4_awburst_o;
    output  [2:0]  m_axi4_awprot_o;
    input  m_axi4_wready_i;
    output  m_axi4_wvalid_o;
    output  [31:0]  m_axi4_wdata_o;
    output  [3:0]  m_axi4_wstrb_o;
    output  m_axi4_wlast_o;
    output  m_axi4_bready_o;
    input  m_axi4_bvalid_i;
    input  [2:0]  m_axi4_bid_i;
    input  [1:0]  m_axi4_bresp_i;
    input  m_axi4_arready_i;
    output  m_axi4_arvalid_o;
    output  [2:0]  m_axi4_arid_o;
    output  [31:0]  m_axi4_araddr_o;
    output  [7:0]  m_axi4_arlen_o;
    output  [2:0]  m_axi4_arsize_o;
    output  [1:0]  m_axi4_arburst_o;
    output  [2:0]  m_axi4_arprot_o;
    input  m_axi4_rvalid_i;
    output  m_axi4_rready_o;
    input  [2:0]  m_axi4_rid_i;
    input  [31:0]  m_axi4_rdata_i;
    input  [1:0]  m_axi4_rresp_i;
    input  m_axi4_rlast_i;
    input  s_apb_penable_i;
    input  s_apb_psel_i;
    input  s_apb_pwrite_i;
    input  [31:0]  s_apb_paddr_i;
    input  [31:0]  s_apb_pwdata_i;
    output  s_apb_pready_o;
    output  s_apb_pslverr_o;
    output  [31:0]  s_apb_prdata_o;
endmodule