/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.1.0.2506031608
    Soft IP Version: 2.1.0
    2025 10 15 16:17:29
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module axi4_bus0 (axi_aclk_i, axi_aresetn_i, axi_S01_awvalid_i, axi_S01_awid_i,
    axi_S01_awaddr_i, axi_S01_awlen_i, axi_S01_awsize_i, axi_S01_awburst_i,
    axi_S01_awlock_i, axi_S01_awcache_i, axi_S01_awprot_i, axi_S01_awqos_i,
    axi_S01_awregion_i, axi_S01_awuser_i, axi_S01_awready_o, axi_S01_wvalid_i,
    axi_S01_wdata_i, axi_S01_wstrb_i, axi_S01_wlast_i, axi_S01_wuser_i,
    axi_S01_wready_o, axi_S01_bready_i, axi_S01_bvalid_o, axi_S01_bid_o,
    axi_S01_bresp_o, axi_S01_buser_o, axi_S01_arvalid_i, axi_S01_arid_i,
    axi_S01_araddr_i, axi_S01_arlen_i, axi_S01_arsize_i, axi_S01_arburst_i,
    axi_S01_arlock_i, axi_S01_arcache_i, axi_S01_arprot_i, axi_S01_arqos_i,
    axi_S01_arregion_i, axi_S01_aruser_i, axi_S01_arready_o, axi_S01_rready_i,
    axi_S01_rvalid_o, axi_S01_rid_o, axi_S01_rdata_o, axi_S01_rresp_o,
    axi_S01_rlast_o, axi_S01_ruser_o, axi_S00_awvalid_i, axi_S00_awid_i,
    axi_S00_awaddr_i, axi_S00_awlen_i, axi_S00_awsize_i, axi_S00_awburst_i,
    axi_S00_awlock_i, axi_S00_awcache_i, axi_S00_awprot_i, axi_S00_awqos_i,
    axi_S00_awregion_i, axi_S00_awuser_i, axi_S00_awready_o, axi_S00_wvalid_i,
    axi_S00_wdata_i, axi_S00_wstrb_i, axi_S00_wlast_i, axi_S00_wuser_i,
    axi_S00_wready_o, axi_S00_bready_i, axi_S00_bvalid_o, axi_S00_bid_o,
    axi_S00_bresp_o, axi_S00_buser_o, axi_S00_arvalid_i, axi_S00_arid_i,
    axi_S00_araddr_i, axi_S00_arlen_i, axi_S00_arsize_i, axi_S00_arburst_i,
    axi_S00_arlock_i, axi_S00_arcache_i, axi_S00_arprot_i, axi_S00_arqos_i,
    axi_S00_arregion_i, axi_S00_aruser_i, axi_S00_arready_o, axi_S00_rready_i,
    axi_S00_rvalid_o, axi_S00_rid_o, axi_S00_rdata_o, axi_S00_rresp_o,
    axi_S00_rlast_o, axi_S00_ruser_o, axi_M01_awvalid_o, axi_M01_awid_o,
    axi_M01_awaddr_o, axi_M01_awlen_o, axi_M01_awsize_o, axi_M01_awburst_o,
    axi_M01_awlock_o, axi_M01_awcache_o, axi_M01_awprot_o, axi_M01_awqos_o,
    axi_M01_awregion_o, axi_M01_awuser_o, axi_M01_awready_i, axi_M01_wvalid_o,
    axi_M01_wdata_o, axi_M01_wstrb_o, axi_M01_wlast_o, axi_M01_wuser_o,
    axi_M01_wready_i, axi_M01_bvalid_i, axi_M01_bid_i, axi_M01_bresp_i,
    axi_M01_buser_i, axi_M01_bready_o, axi_M01_arvalid_o, axi_M01_arid_o,
    axi_M01_araddr_o, axi_M01_arlen_o, axi_M01_arsize_o, axi_M01_arburst_o,
    axi_M01_arlock_o, axi_M01_arcache_o, axi_M01_arprot_o, axi_M01_arqos_o,
    axi_M01_arregion_o, axi_M01_aruser_o, axi_M01_arready_i, axi_M01_rvalid_i,
    axi_M01_rid_i, axi_M01_rdata_i, axi_M01_rresp_i, axi_M01_rlast_i,
    axi_M01_ruser_i, axi_M01_rready_o, axi_M00_awvalid_o, axi_M00_awid_o,
    axi_M00_awaddr_o, axi_M00_awlen_o, axi_M00_awsize_o, axi_M00_awburst_o,
    axi_M00_awlock_o, axi_M00_awcache_o, axi_M00_awprot_o, axi_M00_awqos_o,
    axi_M00_awregion_o, axi_M00_awuser_o, axi_M00_awready_i, axi_M00_wvalid_o,
    axi_M00_wdata_o, axi_M00_wstrb_o, axi_M00_wlast_o, axi_M00_wuser_o,
    axi_M00_wready_i, axi_M00_bvalid_i, axi_M00_bid_i, axi_M00_bresp_i,
    axi_M00_buser_i, axi_M00_bready_o, axi_M00_arvalid_o, axi_M00_arid_o,
    axi_M00_araddr_o, axi_M00_arlen_o, axi_M00_arsize_o, axi_M00_arburst_o,
    axi_M00_arlock_o, axi_M00_arcache_o, axi_M00_arprot_o, axi_M00_arqos_o,
    axi_M00_arregion_o, axi_M00_aruser_o, axi_M00_arready_i, axi_M00_rvalid_i,
    axi_M00_rid_i, axi_M00_rdata_i, axi_M00_rresp_i, axi_M00_rlast_i,
    axi_M00_ruser_i, axi_M00_rready_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  axi_aclk_i;
    input  axi_aresetn_i;
    input  [0:0]  axi_S01_awvalid_i;
    input  [2:0]  axi_S01_awid_i;
    input  [31:0]  axi_S01_awaddr_i;
    input  [7:0]  axi_S01_awlen_i;
    input  [2:0]  axi_S01_awsize_i;
    input  [1:0]  axi_S01_awburst_i;
    input  [0:0]  axi_S01_awlock_i;
    input  [3:0]  axi_S01_awcache_i;
    input  [2:0]  axi_S01_awprot_i;
    input  [3:0]  axi_S01_awqos_i;
    input  [3:0]  axi_S01_awregion_i;
    input  [0:0]  axi_S01_awuser_i;
    output  [0:0]  axi_S01_awready_o;
    input  [0:0]  axi_S01_wvalid_i;
    input  [31:0]  axi_S01_wdata_i;
    input  [3:0]  axi_S01_wstrb_i;
    input  [0:0]  axi_S01_wlast_i;
    input  [0:0]  axi_S01_wuser_i;
    output  [0:0]  axi_S01_wready_o;
    input  [0:0]  axi_S01_bready_i;
    output  [0:0]  axi_S01_bvalid_o;
    output  [2:0]  axi_S01_bid_o;
    output  [1:0]  axi_S01_bresp_o;
    output  [0:0]  axi_S01_buser_o;
    input  [0:0]  axi_S01_arvalid_i;
    input  [2:0]  axi_S01_arid_i;
    input  [31:0]  axi_S01_araddr_i;
    input  [7:0]  axi_S01_arlen_i;
    input  [2:0]  axi_S01_arsize_i;
    input  [1:0]  axi_S01_arburst_i;
    input  [0:0]  axi_S01_arlock_i;
    input  [3:0]  axi_S01_arcache_i;
    input  [2:0]  axi_S01_arprot_i;
    input  [3:0]  axi_S01_arqos_i;
    input  [3:0]  axi_S01_arregion_i;
    input  [0:0]  axi_S01_aruser_i;
    output  [0:0]  axi_S01_arready_o;
    input  [0:0]  axi_S01_rready_i;
    output  [0:0]  axi_S01_rvalid_o;
    output  [2:0]  axi_S01_rid_o;
    output  [31:0]  axi_S01_rdata_o;
    output  [1:0]  axi_S01_rresp_o;
    output  [0:0]  axi_S01_rlast_o;
    output  [0:0]  axi_S01_ruser_o;
    input  [0:0]  axi_S00_awvalid_i;
    input  [2:0]  axi_S00_awid_i;
    input  [31:0]  axi_S00_awaddr_i;
    input  [7:0]  axi_S00_awlen_i;
    input  [2:0]  axi_S00_awsize_i;
    input  [1:0]  axi_S00_awburst_i;
    input  [0:0]  axi_S00_awlock_i;
    input  [3:0]  axi_S00_awcache_i;
    input  [2:0]  axi_S00_awprot_i;
    input  [3:0]  axi_S00_awqos_i;
    input  [3:0]  axi_S00_awregion_i;
    input  [0:0]  axi_S00_awuser_i;
    output  [0:0]  axi_S00_awready_o;
    input  [0:0]  axi_S00_wvalid_i;
    input  [31:0]  axi_S00_wdata_i;
    input  [3:0]  axi_S00_wstrb_i;
    input  [0:0]  axi_S00_wlast_i;
    input  [0:0]  axi_S00_wuser_i;
    output  [0:0]  axi_S00_wready_o;
    input  [0:0]  axi_S00_bready_i;
    output  [0:0]  axi_S00_bvalid_o;
    output  [2:0]  axi_S00_bid_o;
    output  [1:0]  axi_S00_bresp_o;
    output  [0:0]  axi_S00_buser_o;
    input  [0:0]  axi_S00_arvalid_i;
    input  [2:0]  axi_S00_arid_i;
    input  [31:0]  axi_S00_araddr_i;
    input  [7:0]  axi_S00_arlen_i;
    input  [2:0]  axi_S00_arsize_i;
    input  [1:0]  axi_S00_arburst_i;
    input  [0:0]  axi_S00_arlock_i;
    input  [3:0]  axi_S00_arcache_i;
    input  [2:0]  axi_S00_arprot_i;
    input  [3:0]  axi_S00_arqos_i;
    input  [3:0]  axi_S00_arregion_i;
    input  [0:0]  axi_S00_aruser_i;
    output  [0:0]  axi_S00_arready_o;
    input  [0:0]  axi_S00_rready_i;
    output  [0:0]  axi_S00_rvalid_o;
    output  [2:0]  axi_S00_rid_o;
    output  [31:0]  axi_S00_rdata_o;
    output  [1:0]  axi_S00_rresp_o;
    output  [0:0]  axi_S00_rlast_o;
    output  [0:0]  axi_S00_ruser_o;
    output  [0:0]  axi_M01_awvalid_o;
    output  [3:0]  axi_M01_awid_o;
    output  [31:0]  axi_M01_awaddr_o;
    output  [7:0]  axi_M01_awlen_o;
    output  [2:0]  axi_M01_awsize_o;
    output  [1:0]  axi_M01_awburst_o;
    output  [0:0]  axi_M01_awlock_o;
    output  [3:0]  axi_M01_awcache_o;
    output  [2:0]  axi_M01_awprot_o;
    output  [3:0]  axi_M01_awqos_o;
    output  [3:0]  axi_M01_awregion_o;
    output  [0:0]  axi_M01_awuser_o;
    input  [0:0]  axi_M01_awready_i;
    output  [0:0]  axi_M01_wvalid_o;
    output  [31:0]  axi_M01_wdata_o;
    output  [3:0]  axi_M01_wstrb_o;
    output  [0:0]  axi_M01_wlast_o;
    output  [0:0]  axi_M01_wuser_o;
    input  [0:0]  axi_M01_wready_i;
    input  [0:0]  axi_M01_bvalid_i;
    input  [3:0]  axi_M01_bid_i;
    input  [1:0]  axi_M01_bresp_i;
    input  [0:0]  axi_M01_buser_i;
    output  [0:0]  axi_M01_bready_o;
    output  [0:0]  axi_M01_arvalid_o;
    output  [3:0]  axi_M01_arid_o;
    output  [31:0]  axi_M01_araddr_o;
    output  [7:0]  axi_M01_arlen_o;
    output  [2:0]  axi_M01_arsize_o;
    output  [1:0]  axi_M01_arburst_o;
    output  [0:0]  axi_M01_arlock_o;
    output  [3:0]  axi_M01_arcache_o;
    output  [2:0]  axi_M01_arprot_o;
    output  [3:0]  axi_M01_arqos_o;
    output  [3:0]  axi_M01_arregion_o;
    output  [0:0]  axi_M01_aruser_o;
    input  [0:0]  axi_M01_arready_i;
    input  [0:0]  axi_M01_rvalid_i;
    input  [3:0]  axi_M01_rid_i;
    input  [31:0]  axi_M01_rdata_i;
    input  [1:0]  axi_M01_rresp_i;
    input  [0:0]  axi_M01_rlast_i;
    input  [0:0]  axi_M01_ruser_i;
    output  [0:0]  axi_M01_rready_o;
    output  [0:0]  axi_M00_awvalid_o;
    output  [3:0]  axi_M00_awid_o;
    output  [31:0]  axi_M00_awaddr_o;
    output  [7:0]  axi_M00_awlen_o;
    output  [2:0]  axi_M00_awsize_o;
    output  [1:0]  axi_M00_awburst_o;
    output  [0:0]  axi_M00_awlock_o;
    output  [3:0]  axi_M00_awcache_o;
    output  [2:0]  axi_M00_awprot_o;
    output  [3:0]  axi_M00_awqos_o;
    output  [3:0]  axi_M00_awregion_o;
    output  [0:0]  axi_M00_awuser_o;
    input  [0:0]  axi_M00_awready_i;
    output  [0:0]  axi_M00_wvalid_o;
    output  [31:0]  axi_M00_wdata_o;
    output  [3:0]  axi_M00_wstrb_o;
    output  [0:0]  axi_M00_wlast_o;
    output  [0:0]  axi_M00_wuser_o;
    input  [0:0]  axi_M00_wready_i;
    input  [0:0]  axi_M00_bvalid_i;
    input  [3:0]  axi_M00_bid_i;
    input  [1:0]  axi_M00_bresp_i;
    input  [0:0]  axi_M00_buser_i;
    output  [0:0]  axi_M00_bready_o;
    output  [0:0]  axi_M00_arvalid_o;
    output  [3:0]  axi_M00_arid_o;
    output  [31:0]  axi_M00_araddr_o;
    output  [7:0]  axi_M00_arlen_o;
    output  [2:0]  axi_M00_arsize_o;
    output  [1:0]  axi_M00_arburst_o;
    output  [0:0]  axi_M00_arlock_o;
    output  [3:0]  axi_M00_arcache_o;
    output  [2:0]  axi_M00_arprot_o;
    output  [3:0]  axi_M00_arqos_o;
    output  [3:0]  axi_M00_arregion_o;
    output  [0:0]  axi_M00_aruser_o;
    input  [0:0]  axi_M00_arready_i;
    input  [0:0]  axi_M00_rvalid_i;
    input  [3:0]  axi_M00_rid_i;
    input  [31:0]  axi_M00_rdata_i;
    input  [1:0]  axi_M00_rresp_i;
    input  [0:0]  axi_M00_rlast_i;
    input  [0:0]  axi_M00_ruser_i;
    output  [0:0]  axi_M00_rready_o;
endmodule