/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.1.0.2506031608
    Soft IP Version: 1.5.2
    2025 10 16 14:10:10
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module tcm0 (sys_clk, sys_rst_n, ibus_cmd_valid, ibus_cmd_ready,
    ibus_cmd_payload_wr, ibus_cmd_payload_uncached, ibus_cmd_payload_address,
    ibus_cmd_payload_data, ibus_cmd_payload_mask, ibus_cmd_payload_size,
    ibus_cmd_payload_last, ibus_rsp_valid, ibus_rsp_payload_last,
    ibus_rsp_payload_data, ibus_rsp_payload_error, dbus_cmd_valid,
    dbus_cmd_ready, dbus_cmd_payload_wr, dbus_cmd_payload_uncached,
    dbus_cmd_payload_address, dbus_cmd_payload_data, dbus_cmd_payload_mask,
    dbus_cmd_payload_size, dbus_cmd_payload_last, dbus_rsp_valid,
    dbus_rsp_payload_last, dbus_rsp_payload_data, dbus_rsp_payload_error,
    dbus_rsp_payload_exclusive, dbus_cmd_payload_exclusive, dbus_inv_valid,
    dbus_inv_ready, dbus_inv_payload_last, dbus_inv_payload_fragment_enable,
    dbus_inv_payload_fragment_address, dbus_ack_valid, dbus_ack_ready,
    dbus_ack_payload_last, dbus_ack_payload_fragment_hit)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  sys_clk;
    input  sys_rst_n;
    input  ibus_cmd_valid;
    output  ibus_cmd_ready;
    input  ibus_cmd_payload_wr;
    input  ibus_cmd_payload_uncached;
    input  [31:0]  ibus_cmd_payload_address;
    input  [31:0]  ibus_cmd_payload_data;
    input  [3:0]  ibus_cmd_payload_mask;
    input  [2:0]  ibus_cmd_payload_size;
    input  ibus_cmd_payload_last;
    output  ibus_rsp_valid;
    output  ibus_rsp_payload_last;
    output  [31:0]  ibus_rsp_payload_data;
    output  ibus_rsp_payload_error;
    input  dbus_cmd_valid;
    output  dbus_cmd_ready;
    input  dbus_cmd_payload_wr;
    input  dbus_cmd_payload_uncached;
    input  [31:0]  dbus_cmd_payload_address;
    input  [31:0]  dbus_cmd_payload_data;
    input  [3:0]  dbus_cmd_payload_mask;
    input  [2:0]  dbus_cmd_payload_size;
    input  dbus_cmd_payload_last;
    output  dbus_rsp_valid;
    output  dbus_rsp_payload_last;
    output  [31:0]  dbus_rsp_payload_data;
    output  dbus_rsp_payload_error;
    output  dbus_rsp_payload_exclusive;
    input  dbus_cmd_payload_exclusive;
    output  dbus_inv_valid;
    input  dbus_inv_ready;
    output  dbus_inv_payload_last;
    output  dbus_inv_payload_fragment_enable;
    output  [31:0]  dbus_inv_payload_fragment_address;
    input  dbus_ack_valid;
    output  dbus_ack_ready;
    input  dbus_ack_payload_last;
    input  dbus_ack_payload_fragment_hit;
endmodule