/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.1.0.2506031608
    Soft IP Version: 2.4.0
    2025 10 16 14:11:59
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module sysmem0 (axi_aclk_i, axi_resetn_i, axi_s0_awaddr_i, axi_s0_awvalid_i,
    axi_s0_awprot_i, axi_s0_awready_o, axi_s0_awid_i, axi_s0_awlen_i,
    axi_s0_awsize_i, axi_s0_awburst_i, axi_s0_awlock_i, axi_s0_awcache_i,
    axi_s0_awqos_i, axi_s0_awregion_i, axi_s0_wdata_i, axi_s0_wstrb_i,
    axi_s0_wvalid_i, axi_s0_wready_o, axi_s0_wlast_i, axi_s0_bready_i,
    axi_s0_bresp_o, axi_s0_bvalid_o, axi_s0_bid_o, axi_s0_araddr_i,
    axi_s0_arvalid_i, axi_s0_arprot_i, axi_s0_arready_o, axi_s0_arid_i,
    axi_s0_arlen_i, axi_s0_arsize_i, axi_s0_arburst_i, axi_s0_arlock_i,
    axi_s0_arcache_i, axi_s0_arqos_i, axi_s0_arregion_i, axi_s0_rdata_o,
    axi_s0_rready_i, axi_s0_rresp_o, axi_s0_rvalid_o, axi_s0_rid_o,
    axi_s0_rlast_o, axi_s1_awaddr_i, axi_s1_awvalid_i, axi_s1_awprot_i,
    axi_s1_awready_o, axi_s1_awid_i, axi_s1_awlen_i, axi_s1_awsize_i,
    axi_s1_awburst_i, axi_s1_awlock_i, axi_s1_awcache_i, axi_s1_awqos_i,
    axi_s1_awregion_i, axi_s1_wdata_i, axi_s1_wstrb_i, axi_s1_wvalid_i,
    axi_s1_wready_o, axi_s1_wlast_i, axi_s1_bready_i, axi_s1_bresp_o,
    axi_s1_bvalid_o, axi_s1_bid_o, axi_s1_araddr_i, axi_s1_arvalid_i,
    axi_s1_arprot_i, axi_s1_arready_o, axi_s1_arid_i, axi_s1_arlen_i,
    axi_s1_arsize_i, axi_s1_arburst_i, axi_s1_arlock_i, axi_s1_arcache_i,
    axi_s1_arqos_i, axi_s1_arregion_i, axi_s1_rdata_o, axi_s1_rready_i,
    axi_s1_rresp_o, axi_s1_rvalid_o, axi_s1_rid_o, axi_s1_rlast_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  axi_aclk_i;
    input  axi_resetn_i;
    input  [31:0]  axi_s0_awaddr_i;
    input  axi_s0_awvalid_i;
    input  [2:0]  axi_s0_awprot_i;
    output  axi_s0_awready_o;
    input  [3:0]  axi_s0_awid_i;
    input  [7:0]  axi_s0_awlen_i;
    input  [2:0]  axi_s0_awsize_i;
    input  [1:0]  axi_s0_awburst_i;
    input  axi_s0_awlock_i;
    input  [3:0]  axi_s0_awcache_i;
    input  [3:0]  axi_s0_awqos_i;
    input  [3:0]  axi_s0_awregion_i;
    input  [31:0]  axi_s0_wdata_i;
    input  [3:0]  axi_s0_wstrb_i;
    input  axi_s0_wvalid_i;
    output  axi_s0_wready_o;
    input  axi_s0_wlast_i;
    input  axi_s0_bready_i;
    output  [1:0]  axi_s0_bresp_o;
    output  axi_s0_bvalid_o;
    output  [3:0]  axi_s0_bid_o;
    input  [31:0]  axi_s0_araddr_i;
    input  axi_s0_arvalid_i;
    input  [2:0]  axi_s0_arprot_i;
    output  axi_s0_arready_o;
    input  [3:0]  axi_s0_arid_i;
    input  [7:0]  axi_s0_arlen_i;
    input  [2:0]  axi_s0_arsize_i;
    input  [1:0]  axi_s0_arburst_i;
    input  axi_s0_arlock_i;
    input  [3:0]  axi_s0_arcache_i;
    input  [3:0]  axi_s0_arqos_i;
    input  [3:0]  axi_s0_arregion_i;
    output  [31:0]  axi_s0_rdata_o;
    input  axi_s0_rready_i;
    output  [1:0]  axi_s0_rresp_o;
    output  axi_s0_rvalid_o;
    output  [3:0]  axi_s0_rid_o;
    output  axi_s0_rlast_o;
    input  [31:0]  axi_s1_awaddr_i;
    input  axi_s1_awvalid_i;
    input  [2:0]  axi_s1_awprot_i;
    output  axi_s1_awready_o;
    input  [3:0]  axi_s1_awid_i;
    input  [7:0]  axi_s1_awlen_i;
    input  [2:0]  axi_s1_awsize_i;
    input  [1:0]  axi_s1_awburst_i;
    input  axi_s1_awlock_i;
    input  [3:0]  axi_s1_awcache_i;
    input  [3:0]  axi_s1_awqos_i;
    input  [3:0]  axi_s1_awregion_i;
    input  [31:0]  axi_s1_wdata_i;
    input  [3:0]  axi_s1_wstrb_i;
    input  axi_s1_wvalid_i;
    output  axi_s1_wready_o;
    input  axi_s1_wlast_i;
    input  axi_s1_bready_i;
    output  [1:0]  axi_s1_bresp_o;
    output  axi_s1_bvalid_o;
    output  [3:0]  axi_s1_bid_o;
    input  [31:0]  axi_s1_araddr_i;
    input  axi_s1_arvalid_i;
    input  [2:0]  axi_s1_arprot_i;
    output  axi_s1_arready_o;
    input  [3:0]  axi_s1_arid_i;
    input  [7:0]  axi_s1_arlen_i;
    input  [2:0]  axi_s1_arsize_i;
    input  [1:0]  axi_s1_arburst_i;
    input  axi_s1_arlock_i;
    input  [3:0]  axi_s1_arcache_i;
    input  [3:0]  axi_s1_arqos_i;
    input  [3:0]  axi_s1_arregion_i;
    output  [31:0]  axi_s1_rdata_o;
    input  axi_s1_rready_i;
    output  [1:0]  axi_s1_rresp_o;
    output  axi_s1_rvalid_o;
    output  [3:0]  axi_s1_rid_o;
    output  axi_s1_rlast_o;
endmodule