/*   ==================================================================

>>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
------------------------------------------------------------------
Copyright (c) 2025-2025 by Lattice Semiconductor Corporation
ALL RIGHTS RESERVED
------------------------------------------------------------------

  IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™
  DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.

  Lattice grants permission to use this code pursuant to the
  terms of the Lattice Propel License Agreement.

DISCLAIMER:

LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS,
WHETHER EXPRESSED, IMPLIED, STATUTORY,
OR IN ANY PROVISION OF THE LATTICE PROPEL LICENSE AGREEMENT OR
COMMUNICATION WITH LICENSEE,
AND LATTICE SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF
MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
LATTICE DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED HEREIN WILL MEET
LICENSEE 'S REQUIREMENTS, OR THAT LICENSEE' S OPERATION OF ANY DEVICE,
SOFTWARE OR SYSTEM USING THIS FILE OR ITS CONTENTS WILL BE
UNINTERRUPTED OR ERROR FREE,
OR THAT DEFECTS HEREIN WILL BE CORRECTED.
LICENSEE ASSUMES RESPONSIBILITY FOR SELECTION OF MATERIALS TO ACHIEVE
ITS INTENDED RESULTS, AND FOR THE PROPER INSTALLATION, USE,
AND RESULTS OBTAINED THEREFROM.
LICENSEE ASSUMES THE ENTIRE RISK OF THE FILE AND ITS CONTENTS PROVING
DEFECTIVE OR FAILING TO PERFORM PROPERLY AND IN SUCH EVENT,
LICENSEE SHALL ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, SERVICE,
CORRECTION,
OR ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR ASSOCIATED WITH THE
SOFTWARE.IN NO EVENT SHALL LATTICE BE LIABLE TO ANY PARTY FOR DIRECT,
INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
INCLUDING LOST PROFITS,
ARISING OUT OF THE USE OF THIS FILE OR ITS CONTENTS,
EVEN IF LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
LATTICE 'S SOLE LIABILITY, AND LICENSEE' S SOLE REMEDY,
IS SET FORTH ABOVE.
LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE,
ITS CONTENTS OR USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES'
INTELLECTUAL PROPERTY RIGHTS, INCLUDING ANY PATENT. IT IS THE USER' S
RESPONSIBILITY TO VERIFY THE USER SOFTWARE DESIGN FOR CONSISTENCY AND
FUNCTIONALITY THROUGH THE USE OF FORMAL SOFTWARE VALIDATION METHODS.
------------------------------------------------------------------

================================================================== */
#ifndef EMMC_CONTROLLER_H_
#define EMMC_CONTROLLER_H_

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#define EMMC_CONTROLLER_DRV_VER "v25.2.0"

//Success and Failure
#define FAILURE                         0
#define SUCCESS                         1

//Set And Clear
#define GET_REG_MASK(F_LEN,F_IDX)       (unsigned int)(((0x00000001 << F_LEN) - 1) << F_IDX)
#define PUT_FIELD_VAL(F_VALUE,F_LEN,\
                      F_IDX)            (unsigned int)((unsigned int)(F_VALUE << F_IDX) & GET_REG_MASK(F_LEN,F_IDX))
#define SET_REG_FIELD(REG_VAR,F_VALUE,\
                      F_LEN,F_IDX)      REG_VAR = (unsigned int)(((unsigned int)REG_VAR & ~(GET_REG_MASK(F_LEN,F_IDX))) | \
                                                                PUT_FIELD_VAL(F_VALUE,F_LEN,F_IDX))

#define CLEAR                           0x00000000
#define SET_ALL_BITS                    0xFFFFFFFF
#define ZERO                            0
#define DAT32B_SWAP_BYTES(DATA)         ((DATA >> 24) & 0xFF      ) | \
                                        ((DATA >>  8) & 0xFF00    ) | \
                                        ((DATA <<  8) & 0xFF0000  ) | \
                                        ((DATA << 24) & 0xFF000000)

#define DAT24B_SWAP_BYTES(DATA)         ((DATA >> 16) & 0xFF      ) | \
                                        ((DATA      ) & 0xFF00    ) | \
                                        ((DATA << 16) & 0xFF0000  )

#define GET8B_AND_CONCAT4X(DATA)        ((0xFF & DATA)      ) | \
                                        ((0xFF & DATA) <<  8) | \
                                        ((0xFF & DATA) << 16) | \
                                        ((0xFF & DATA) << 24)

#define GET_FIELD_VAL(DATA, F_IDX,\
                      F_LEN)            (((DATA) >> (F_IDX)) & ((1 << (F_LEN)) - 1))

#define CALC_DWORD_LEN(BYTE_LEN)        ((BYTE_LEN >> 2) + ((BYTE_LEN & 0x3)?  1 : 0))

#define MHZ_TO_KHZ(CLK_FREQ_M)          (CLK_FREQ_M*1000)
#define KHZ_TO_MHZ(CLK_FREQ_K)          (CLK_FREQ_K/1000)

// Register Offset
#define EMMC_ADR_IPCORE_ID              0x000
#define EMMC_ADR_INT_ENABLE             0x004
#define EMMC_ADR_CONFIG0                0x008
#define EMMC_ADR_CONFIG1                0x00C

#define EMMC_ADR_INFO_STATUS            0x100
#define EMMC_ADR_INT_STATUS             0x104
#define EMMC_ADR_RESP_D0                0x108
#define EMMC_ADR_RESP_D1                0x10C
#define EMMC_ADR_RESP_D2                0x110
#define EMMC_ADR_RESP_D3                0x114
#define EMMC_ADR_RESP_D4                0x118

#define EMMC_ADR_SOFT_RESET             0x200
#define EMMC_ADR_INT_SET                0x204
#define EMMC_ADR_SRC_DST                0x208
#define EMMC_ADR_CTRL0                  0x20C
#define EMMC_ADR_CTRL1                  0x210
#define EMMC_ADR_CTRL2                  0x214

// Soft Reset bit fields
#define IP_CORE_RST                     0x00000001
#define EMMC_TGT_RST                    0x00000002

#define EMMC_INT_DAT_TIMEOUT            0x00200000
#define EMMC_INT_CMD_TIMEOUT            0x00100000
#define EMMC_INT_BUS_RD_ERROR           0x00080000
#define EMMC_INT_BUS_WR_ERROR           0x00040000
#define EMMC_INT_DAT_CRC_ERROR          0x00020000
#define EMMC_INT_CMD_CRC_ERROR          0x00010000
#define EMMC_INT_CMD_DONE               0x00000001

#define EMMC_INT_DAT_TIMEOUT_IDX        21
#define EMMC_INT_CMD_TIMEOUT_IDX        20
#define EMMC_INT_BUS_RD_ERROR_IDX       19
#define EMMC_INT_BUS_WR_ERROR_IDX       18
#define EMMC_INT_DAT_CRC_ERROR_IDX      17
#define EMMC_INT_CMD_CRC_ERROR_IDX      16
#define EMMC_INT_CMD_DONE_IDX           0

#define EMMC_CFG0_SCK_RATE              0x0000FFFF
#define EMMC_CFG0_PP1_OD0               0x00010000
#define EMMC_CFG0_DDR_MODE              0x00020000
#define EMMC_CFG0_IO_WIDTH              0x00300000

#define EMMC_CFG0_SCK_RATE_IDX          0
#define EMMC_CFG0_PP1_OD0_IDX           16
#define EMMC_CFG0_DDR_MODE_IDX          17
#define EMMC_CFG0_IO_WIDTH_IDX          20

#define EMMC_CFG1_CMD_TIMEOUT           0x0000FFFF
#define EMMC_CFG1_DAT_TIMEOUT           0xFFFF0000

#define EMMC_CFG1_CMD_TIMEOUT_IDX       0
#define EMMC_CFG1_DAT_TIMEOUT_IDX       16

#define EMMC_CTRL0_BLOCK_LEN            0x0000000F
#define EMMC_CTRL0_NUM_BLOCKS           0xFFFF0000

#define EMMC_CTRL0_BLOCK_LEN_IDX        0
#define EMMC_CTRL0_NUM_BLOCKS_IDX       16

#define EMMC_CTRL2_CMD_CODE             0x0000003F
#define EMMC_CTRL2_START                0x00000080
#define EMMC_CTRL2_BOOT                 0x00000100

#define EMMC_CTRL2_CMD_CODE_IDX         0
#define EMMC_CTRL2_START_IDX            7
#define EMMC_CTRL2_BOOT_IDX             8

#define EMMC_INFO_STS_BUSY              0x00000001

#define EMMC_IO_X1                      0
#define EMMC_IO_X4                      2
#define EMMC_IO_X8                      3

#define EMMC_SDR                        0
#define EMMC_DDR                        1

#define EMMC_OPEN_DRAIN                 0
#define EMMC_PUSH_PULL                  1

// eMMC Basic Commands
#define EMMC_CMD_GO_IDLE_STATE          0
#define EMMC_CMD_SEND_OP_COND           1
#define EMMC_CMD_ALL_SEND_CID           2
#define EMMC_CMD_SET_RELATIVE_ADDR      3
#define EMMC_CMD_SET_DSR                4
#define EMMC_CMD_SLEEP_AWAKE            5
#define EMMC_CMD_SWITCH                 6
#define EMMC_CMD_SELECT_CARD            7
#define EMMC_CMD_SEND_EXT_CSD           8
#define EMMC_CMD_SEND_CSD               9
#define EMMC_CMD_SEND_CID               10
#define EMMC_CMD_STOP_TRANSFER          12
#define EMMC_CMD_SEND_STATUS            13
#define EMMC_CMD_BUS_TEST_R             14
#define EMMC_CMD_GO_INACTIVE_STATE      15
#define EMMC_CMD_BUS_TEST_W             19
// eMMC Block Read Commands
#define EMMC_CMD_SET_BLOCKLEN           16
#define EMMC_CMD_RD_BLOCK_ONE           17
#define EMMC_CMD_RD_BLOCK_MULT          18
#define EMMC_CMD_SEND_TUNING_BLK        21
// eMMC Block Write Commands
#define EMMC_CMD_SET_BLOCK_COUNT        23
#define EMMC_CMD_WR_BLOCK_ONE           24
#define EMMC_CMD_WR_BLOCK_MULT          25
#define EMMC_CMD_PROGRAM_CID            26
#define EMMC_CMD_PROGRAM_CSD            27
#define EMMC_CMD_SET_TIME               49
// eMMC Write Protect Commands
#define EMMC_CMD_SET_WR_PROT            28
#define EMMC_CMD_CLR_WR_PROT            29
#define EMMC_CMD_SEND_WR_PROT           30
#define EMMC_CMD_SEND_WR_PROT_TYP       31
// eMMC Erase Commands
#define EMMC_CMD_ERASE_GRP_START        35
#define EMMC_CMD_ERASE_GRP_END          36
#define EMMC_CMD_ERASE                  38
// eMMC IO Commands
#define EMMC_CMD_FAST_IO                39
#define EMMC_CMD_GO_IRQ_STATE           40
// eMMC Lock/Unlock Commands
#define EMMC_CMD_LOCK_UNLOCK            42
// eMMC Command Queue Commands
#define EMMC_CMD_QUEUED_TASK_PARAMS     44
#define EMMC_CMD_QUEUED_TASK_ADDR       45
#define EMMC_CMD_EXECUTE_READ_TASK      46
#define EMMC_CMD_EXECUTE_WRITE_TASK     47
#define EMMC_CMD_CMDQ_TASK_MGMT         48
// eMMC Security Protocols Commands
#define EMMC_CMD_PROTOCOL_RD            53
#define EMMC_CMD_PROTOCOL_WR            54
// eMMC Application Specific Commands
#define EMMC_CMD_APP_CMD                55
#define EMMC_CMD_GEN_CMD                56

// eMMC Device Status - index
#define DEVSTAT_ADDR_OUT_OF_RANGE       31
#define DEVSTAT_ADDR_MISALIGNED         30
#define DEVSTAT_BLOCKLEN_ERROR          29
#define DEVSTAT_ERASE_SEQ_ERROR         28
#define DEVSTAT_ERASE_PARAM             27
#define DEVSTAT_WP_VIOLATION            26
#define DEVSTAT_DEVICE_IS_LOCKED        25
#define DEVSTAT_LOCK_UNLOCK_FAILED      24

#define DEVSTAT_COM_CRC_ERROR           23
#define DEVSTAT_ILLEGAL_COMMAND         22
#define DEVSTAT_DEVICE_ECC_FAILED       21
#define DEVSTAT_CC_ERROR                20
#define DEVSTAT_ERROR                   19
#define DEVSTAT_CID_CSD_OVERWRITE       16

#define DEVSTAT_WP_ERASE_SKIP           15
#define DEVSTAT_ERASE_RESET             13
#define DEVSTAT_CURRENT_STATE           12
#define DEVSTAT_READY_FOR_DATA          8

#define DEVSTAT_SWITCH_ERROR            7
#define DEVSTAT_EXCEPTION_EVENT         6
#define DEVSTAT_APP_CMD                 5

#define BLKLEN_16B                      4
#define BLKLEN_32B                      5
#define BLKLEN_64B                      6
#define BLKLEN_128B                     7
#define BLKLEN_256B                     8
#define BLKLEN_512B                     9
#define BLKLEN_1KB                      10
#define BLKLEN_2KB                      11
#define BLKLEN_4KB                      12
#define BLKLEN_8KB                      13
#define BLKLEN_16KB                     14
#define BLKLEN_32KB                     15


typedef struct {
  uint8_t dat_0;
  uint8_t dat_1;
  uint8_t dat_2;
  uint8_t dat_3;
} data_4bytes_t;

typedef struct {
  uint8_t dat_0;
  uint8_t dat_1;
} data_2bytes_t;

typedef struct {
  volatile unsigned int EMMC_REG_IPCORE_ID   ;
  volatile unsigned int EMMC_REG_INT_ENABLE  ;
  volatile unsigned int EMMC_REG_CONFIG0     ;
  volatile unsigned int EMMC_REG_CONFIG1     ;
  volatile unsigned int reserved_00[60]      ;

  volatile unsigned int EMMC_REG_INFO_STATUS ;
  volatile unsigned int EMMC_REG_INT_STATUS  ;
  volatile unsigned int EMMC_REG_RESP_D0     ;
  volatile unsigned int EMMC_REG_RESP_D1     ;
  volatile unsigned int EMMC_REG_RESP_D2     ;
  volatile unsigned int EMMC_REG_RESP_D3     ;
  volatile unsigned int EMMC_REG_RESP_D4     ;
  volatile unsigned int reserved_01[57]      ;

  volatile unsigned int EMMC_REG_SOFT_RESET  ;
  volatile unsigned int EMMC_REG_INT_SET     ;
  volatile unsigned int EMMC_REG_SRC_DST     ;
  volatile unsigned int EMMC_REG_CTRL0       ;
  volatile unsigned int EMMC_REG_CTRL1       ;
  volatile unsigned int EMMC_REG_CTRL2       ;
} emmc_ctl_reg_t;

typedef struct {
  unsigned int init_done;
  unsigned int base_addr;
  unsigned int sck_rate;
  unsigned int io_width;      /*0 - x1, 2 - x4, 3 - x8*/
  unsigned int io_drive;      /*0 - open-drain, 1 - push-pull*/
  unsigned int ddr_mode;      /*0 - SDR, 1 - DDR*/
  unsigned int max_num_lane;
  unsigned int sys_clk_freq_khz;  // in KHz
  unsigned int emmc_sck_freq_khz; // in KHz
  unsigned int interrupt_enable;

  unsigned int emmc_block_size;
  unsigned int min_num_blocks;
  unsigned int max_num_blocks;
  unsigned int tgt_addr;        // {tgt_addr[31:15],16'h0000}

  unsigned int rsp_data[5];     // [0] - response cmd index, [4:1] - response data

} emmc_ctl_handle_t ;

/* Externs */
extern emmc_ctl_handle_t emmc_c0;
extern emmc_ctl_handle_t *emmc_c0_inst;

/* Function headers*/
unsigned char emmc_ctl_init(emmc_ctl_handle_t *handle);
unsigned char set_emmc_clock_freq_khz(emmc_ctl_handle_t *handle, unsigned int sck_freq);
unsigned char set_emmc_ddr_mode(emmc_ctl_handle_t *handle, unsigned int ddr_mode);
unsigned char set_emmc_io_width(emmc_ctl_handle_t *handle, unsigned int io_width);
unsigned char set_emmc_clk_io_config(emmc_ctl_handle_t *handle, unsigned int sck_freq, unsigned int ddr_mode, unsigned int io_width, unsigned int io_drive);
unsigned char emmc_check_error_status(emmc_ctl_handle_t *handle);
unsigned char emmc_get_resp_data(emmc_ctl_handle_t *handle);
unsigned char wait_emmc_ctl_busy_status(emmc_ctl_handle_t *handle, unsigned int wait_value);
unsigned char get_block_size_encoding(unsigned int blocklen);

unsigned char emmc_cmd_go_idle(emmc_ctl_handle_t *handle);
unsigned char emmc_cmd_send_op_cond(emmc_ctl_handle_t *handle);
unsigned char emmc_cmd_all_send_cid(emmc_ctl_handle_t *handle);
unsigned char emmc_cmd_set_relative_addr(emmc_ctl_handle_t *handle, unsigned int tgt_addr);
unsigned char emmc_cmd_switch(emmc_ctl_handle_t *handle, unsigned int access, unsigned int index, unsigned int value, unsigned int cmd_set);
unsigned char emmc_cmd_select_card(emmc_ctl_handle_t *handle);
unsigned char emmc_cmd_deselect_card(emmc_ctl_handle_t *handle);
unsigned char emmc_cmd_send_ext_csd(emmc_ctl_handle_t *handle, unsigned int dst_addr);
unsigned char emmc_cmd_send_csd(emmc_ctl_handle_t *handle);
unsigned char emmc_cmd_send_cid(emmc_ctl_handle_t *handle);
unsigned char emmc_cmd_stop_transmission(emmc_ctl_handle_t *handle);
unsigned char emmc_cmd_send_status(emmc_ctl_handle_t *handle);
unsigned char emmc_cmd_set_block_length(emmc_ctl_handle_t *handle, unsigned int blocklen);
unsigned char emmc_cmd_set_block_count(emmc_ctl_handle_t *handle, unsigned int blockcnt);
unsigned char emmc_cmd_write_block(emmc_ctl_handle_t *handle, unsigned int src_addr);
unsigned char emmc_cmd_read_block(emmc_ctl_handle_t *handle, unsigned int dst_addr);

unsigned char emmc_cmd_bustest_w(emmc_ctl_handle_t *handle, unsigned int src_addr, unsigned int num_bytes);
unsigned char emmc_cmd_bustest_r(emmc_ctl_handle_t *handle, unsigned int dst_addr, unsigned int num_bytes);


#endif /* EMMC_CONTROLLER_H_ */
