/*   ==================================================================

     >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
     ------------------------------------------------------------------
     Copyright (c) 2025-2025 by Lattice Semiconductor Corporation
     ALL RIGHTS RESERVED
     ------------------------------------------------------------------

       IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™
       DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.

       Lattice grants permission to use this code pursuant to the
       terms of the Lattice Propel License Agreement.

     DISCLAIMER:

    LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS,
    WHETHER EXPRESSED, IMPLIED, STATUTORY,
    OR IN ANY PROVISION OF THE LATTICE PROPEL LICENSE AGREEMENT OR
    COMMUNICATION WITH LICENSEE,
    AND LATTICE SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF
    MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
    LATTICE DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED HEREIN WILL MEET
    LICENSEE 'S REQUIREMENTS, OR THAT LICENSEE' S OPERATION OF ANY DEVICE,
    SOFTWARE OR SYSTEM USING THIS FILE OR ITS CONTENTS WILL BE
    UNINTERRUPTED OR ERROR FREE,
    OR THAT DEFECTS HEREIN WILL BE CORRECTED.
    LICENSEE ASSUMES RESPONSIBILITY FOR SELECTION OF MATERIALS TO ACHIEVE
    ITS INTENDED RESULTS, AND FOR THE PROPER INSTALLATION, USE,
    AND RESULTS OBTAINED THEREFROM.
    LICENSEE ASSUMES THE ENTIRE RISK OF THE FILE AND ITS CONTENTS PROVING
    DEFECTIVE OR FAILING TO PERFORM PROPERLY AND IN SUCH EVENT,
    LICENSEE SHALL ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, SERVICE,
    CORRECTION,
    OR ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR ASSOCIATED WITH THE
    SOFTWARE.IN NO EVENT SHALL LATTICE BE LIABLE TO ANY PARTY FOR DIRECT,
    INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
    INCLUDING LOST PROFITS,
    ARISING OUT OF THE USE OF THIS FILE OR ITS CONTENTS,
    EVEN IF LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
    LATTICE 'S SOLE LIABILITY, AND LICENSEE' S SOLE REMEDY,
    IS SET FORTH ABOVE.
    LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE,
    ITS CONTENTS OR USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES'
    INTELLECTUAL PROPERTY RIGHTS, INCLUDING ANY PATENT. IT IS THE USER' S
    RESPONSIBILITY TO VERIFY THE USER SOFTWARE DESIGN FOR CONSISTENCY AND
    FUNCTIONALITY THROUGH THE USE OF FORMAL SOFTWARE VALIDATION METHODS.
     ------------------------------------------------------------------

================================================================== */

#include "emmc_controller.h"

// ------------------------------------------------------------------------------------------------------------
/**
 * @brief   Function to initializes the eMMC Controller IP.
 *
 * This API initializes the eMMC Controller IP with the following actions:
 * - Assigns the base address to the emmc_ctl_reg_t struct.
 * - Initializes the eMMC configuration derived from the input pointer
 *   (refer to the emmc_ctl_handle_t struct).
 * - Enables the interrupt.
 *
 * @param   handle        Pointer of Handle of the emmc_ctl_handle_t structure.
 * @param   base_addr       Base address to be assigned.
 * @return                      Returns 'SUCCESS' (0) on success,
 *                  or 'FAILURE' (1) if input pointer is NULL.
 */

unsigned char emmc_ctl_init( emmc_ctl_handle_t *handle)
{
  unsigned char status = FAILURE;
  unsigned int rdat;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl = (emmc_ctl_reg_t *)(handle->base_addr);

  // Assert IP core reset and target reset
  emmc_ctl->EMMC_REG_SOFT_RESET = 0x3;

  /* Update Configuration 0 register */
  rdat = emmc_ctl->EMMC_REG_CONFIG0;

  SET_REG_FIELD(rdat, handle->sck_rate, 16, EMMC_CFG0_SCK_RATE_IDX);

  emmc_ctl->EMMC_REG_CONFIG0 = rdat;
  emmc_ctl->EMMC_REG_CONFIG1 = 0;

  emmc_ctl->EMMC_REG_INT_ENABLE = handle->interrupt_enable;

  handle->emmc_block_size = 512; // default block size
  handle->tgt_addr        = 0;   // to be assigned later

  // De-assert IP core reset and target reset
  emmc_ctl->EMMC_REG_SOFT_RESET = 0;

  status = SUCCESS;

  return status;
}

// ------------------------------------------------------------------------------------------------------------
/**
 * @brief   Private/Internal function to poll the eMMC status by reading the eMMC
 *          information status register
 *
 * This API is used to poll the eMMC Controller status by reading the
 * information status register (offset 0x100).
 *
 * @param   handle           Handle of the emmc_ctl_handle_t structure
 * @param   wait_value       Expected value for eMMC busy status done
 * @return                   Returns 'SUCCESS' (0) on success,
 *                   or 'FAILURE' (1) if input pointer is NULL.
 */
unsigned char wait_emmc_ctl_busy_status(emmc_ctl_handle_t *handle,
                  unsigned int wait_value)
{
  unsigned char status = FAILURE;
  unsigned int emmc_busy;
  unsigned int wait_done;
  volatile unsigned int rdat;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl  = (emmc_ctl_reg_t *)(handle->base_addr);
  wait_done                 = 0;
  emmc_busy                 = 0;

  do
  {
    rdat = emmc_ctl->EMMC_REG_INFO_STATUS;
    emmc_busy = rdat & EMMC_INFO_STS_BUSY;

    if(emmc_busy == wait_value)
      wait_done = 1;
  }
  while(!wait_done);

  status = SUCCESS;
  return status;
}


// ------------------------------------------------------------------------------------------------------------
/**
 * @brief   Function to set the eMMC clock frequency
 *
 * This API is used to set the eMMC clock frequency.
 *
 * @param   handle           Handle of the emmc_ctl_handle_t structure
 * @param   sck_freq         Clock frequency (in KHz) to be set
 * @return                   Returns 'SUCCESS' (0) on success,
 *                   or 'FAILURE' (1) if input pointer is NULL.
 */

unsigned char set_emmc_clock_freq_khz(emmc_ctl_handle_t *handle,
                unsigned int sck_freq)
{
  unsigned char status = FAILURE;
  unsigned int rdat;
  unsigned int sck_rate;
  unsigned int new_rate;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  rdat     = emmc_ctl->EMMC_REG_CONFIG0;
  sck_rate = GET_FIELD_VAL(rdat,EMMC_CFG0_SCK_RATE_IDX,16);
  new_rate = ((handle->sys_clk_freq_khz + (2 * sck_freq) - 1) / (2 * sck_freq));

  if(sck_freq >= handle->sys_clk_freq_khz)
    new_rate  = 0;

  if(new_rate != sck_rate) {
    /* In case there is ongoing eMMC transaction, wait until it is done */
    wait_emmc_ctl_busy_status(handle,0);
    /* Reprogram new rate */
    SET_REG_FIELD(rdat, new_rate, 16, EMMC_CFG0_SCK_RATE_IDX);
    emmc_ctl->EMMC_REG_CONFIG0  = rdat;
  }

  handle->sck_rate = new_rate;
  handle->emmc_sck_freq_khz = (unsigned int)((new_rate == 0)? handle->sys_clk_freq_khz :
                                                              (handle->sys_clk_freq_khz/new_rate/2));

  status = SUCCESS;
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char set_emmc_ddr_mode(emmc_ctl_handle_t *handle, unsigned int ddr_mode)
{
  unsigned char status = FAILURE;
  unsigned int rdat;
  unsigned int old_ddr_mode;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  rdat          = emmc_ctl->EMMC_REG_CONFIG0;
  old_ddr_mode  = GET_FIELD_VAL(rdat,EMMC_CFG0_DDR_MODE_IDX,1);

  if(ddr_mode != old_ddr_mode) {
    /* In case there is ongoing eMMC transaction, wait until it is done */
    wait_emmc_ctl_busy_status(handle,0);
    /* Reprogram new data rate */
    SET_REG_FIELD(rdat, ddr_mode, 1, EMMC_CFG0_DDR_MODE_IDX);
    emmc_ctl->EMMC_REG_CONFIG0  = rdat;
  }

  handle->ddr_mode = ddr_mode;

  status = SUCCESS;
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char set_emmc_io_width(emmc_ctl_handle_t *handle, unsigned int io_width)
{
  unsigned char status = FAILURE;
  unsigned int rdat;
  unsigned int old_io_width;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  rdat          = emmc_ctl->EMMC_REG_CONFIG0;
  old_io_width  = GET_FIELD_VAL(rdat,EMMC_CFG0_IO_WIDTH_IDX,2);

  if(io_width != old_io_width) {
    /* In case there is ongoing eMMC transaction, wait until it is done */
    wait_emmc_ctl_busy_status(handle,0);
    /* Reprogram new data rate */
    SET_REG_FIELD(rdat, io_width, 2, EMMC_CFG0_IO_WIDTH_IDX);
    emmc_ctl->EMMC_REG_CONFIG0  = rdat;
  }

  handle->io_width = io_width;

  status = SUCCESS;
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char set_emmc_clk_io_config(emmc_ctl_handle_t *handle, unsigned int sck_freq,
                                     unsigned int ddr_mode, unsigned int io_width, unsigned int io_drive)
{
  unsigned char status = FAILURE;
  unsigned int rdat;
  unsigned int sck_rate;
  unsigned int new_rate;
  unsigned int old_ddr_mode;
  unsigned int old_io_width;
  unsigned int old_io_drive;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  rdat          = emmc_ctl->EMMC_REG_CONFIG0;
  sck_rate      = GET_FIELD_VAL(rdat,EMMC_CFG0_SCK_RATE_IDX,16);
  old_ddr_mode  = GET_FIELD_VAL(rdat,EMMC_CFG0_DDR_MODE_IDX,1);
  old_io_width  = GET_FIELD_VAL(rdat,EMMC_CFG0_IO_WIDTH_IDX,2);
  old_io_drive  = GET_FIELD_VAL(rdat,EMMC_CFG0_PP1_OD0_IDX,1);

  new_rate      = ((handle->sys_clk_freq_khz + (2 * sck_freq) - 1) / (2 * sck_freq));

  if(sck_freq >= handle->sys_clk_freq_khz)
    new_rate  = 0;

  if((new_rate != sck_rate) ||
     (ddr_mode != old_ddr_mode) ||
     (io_width != old_io_width) ||
     (io_drive != old_io_drive))
  {
    /* In case there is ongoing eMMC transaction, wait until it is done */
    wait_emmc_ctl_busy_status(handle,0);
    /* Reprogram new config */
    SET_REG_FIELD(rdat, new_rate, 16, EMMC_CFG0_SCK_RATE_IDX);
    SET_REG_FIELD(rdat, ddr_mode, 1,  EMMC_CFG0_DDR_MODE_IDX);
    SET_REG_FIELD(rdat, io_width, 2,  EMMC_CFG0_IO_WIDTH_IDX);
    SET_REG_FIELD(rdat, io_drive, 1,  EMMC_CFG0_PP1_OD0_IDX );

    emmc_ctl->EMMC_REG_CONFIG0  = rdat;
  }

  handle->sck_rate = new_rate;
  handle->ddr_mode = ddr_mode;
  handle->io_width = io_width;
  handle->io_drive = io_drive;

  handle->emmc_sck_freq_khz = (unsigned int)((new_rate == 0)? handle->sys_clk_freq_khz :
                                                              (handle->sys_clk_freq_khz/new_rate/2));

  status = SUCCESS;
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char emmc_check_error_status(emmc_ctl_handle_t *handle)
{
  unsigned char status = FAILURE;
  unsigned int  rdat;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  rdat    = emmc_ctl->EMMC_REG_INT_STATUS;
  // clear interrupt status
  emmc_ctl->EMMC_REG_INT_STATUS = rdat;

  status = ((rdat & 0xFFFFFFFE) == ZERO)? SUCCESS : FAILURE;
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char emmc_get_resp_data(emmc_ctl_handle_t *handle)
{
  unsigned char status = FAILURE;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  handle->rsp_data[0] = emmc_ctl->EMMC_REG_RESP_D0;
  handle->rsp_data[1] = emmc_ctl->EMMC_REG_RESP_D1;
  handle->rsp_data[2] = emmc_ctl->EMMC_REG_RESP_D2;
  handle->rsp_data[3] = emmc_ctl->EMMC_REG_RESP_D3;
  handle->rsp_data[4] = emmc_ctl->EMMC_REG_RESP_D4;

  status = SUCCESS;
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char get_block_size_encoding(unsigned int blocklen)
{
  unsigned char block_size;

  switch (blocklen)
  {
    case 16    : block_size = BLKLEN_16B ; break;
    case 32    : block_size = BLKLEN_32B ; break;
    case 64    : block_size = BLKLEN_64B ; break;
    case 128   : block_size = BLKLEN_128B; break;
    case 256   : block_size = BLKLEN_256B; break;
    case 512   : block_size = BLKLEN_512B; break;
    case 1024  : block_size = BLKLEN_1KB ; break;
    case 2048  : block_size = BLKLEN_2KB ; break;
    case 4096  : block_size = BLKLEN_4KB ; break;
    case 8192  : block_size = BLKLEN_8KB ; break;
    case 16384 : block_size = BLKLEN_16KB; break;
    case 32768 : block_size = BLKLEN_32KB; break;
    default    : block_size = BLKLEN_512B; break;
  }

  return block_size;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char emmc_cmd_go_idle(emmc_ctl_handle_t *handle)
{
  unsigned char status = FAILURE;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  emmc_ctl->EMMC_REG_CONFIG1 = 0;

  emmc_ctl->EMMC_REG_CTRL0 = 0;
  emmc_ctl->EMMC_REG_CTRL1 = 0;
  emmc_ctl->EMMC_REG_CTRL2 = (EMMC_CTRL2_START | EMMC_CMD_GO_IDLE_STATE);

  wait_emmc_ctl_busy_status(handle,0);

  // clear interrupt status
  emmc_ctl->EMMC_REG_INT_STATUS = SET_ALL_BITS;

  status = SUCCESS;
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char emmc_cmd_send_op_cond(emmc_ctl_handle_t *handle)
{
  unsigned char status = FAILURE;
  unsigned int  rdat;
  unsigned int  cmd_arg;
  unsigned char cmd_done;
  unsigned char det_err;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  emmc_ctl->EMMC_REG_CONFIG1 = 0;

  // OCR[31]    = 0x0   -> card power up status
  // OCR[30:29] = 0x2   -> sector mode
  // OCR[28:24] = 0x00  -> reserved
  // OCR[23:15] = 0x1FF -> 2.7-3.6V
  // OCR[14:8]  = 0x00  -> 2.0-2.6V
  // OCR[7]     = 0x1   -> 1.7-1.95V
  // OCR[6:0]   = 0x00  -> reserved
  cmd_arg = 0x40FF8080;

  emmc_ctl->EMMC_REG_CTRL0 = 0;
  emmc_ctl->EMMC_REG_CTRL1 = cmd_arg;


  cmd_done  = 0;
  det_err   = 0;
  do
  {
    emmc_ctl->EMMC_REG_CTRL2 = (EMMC_CTRL2_START | EMMC_CMD_SEND_OP_COND);
    wait_emmc_ctl_busy_status(handle,0);
    rdat = emmc_ctl->EMMC_REG_RESP_D1;

    // read interrupt status, check that it is not due to timeout
    rdat                          = emmc_ctl->EMMC_REG_INT_STATUS;
    cmd_done                      = (GET_FIELD_VAL(rdat,EMMC_INT_CMD_TIMEOUT_IDX,2) == ZERO)? 1 : 0;
    det_err                       = ((rdat & 0xFFFFFFFE) == ZERO)? 0 : 1;

    // check if device is ready (from OCR[31])
    if(cmd_done)
    {
      rdat                        = emmc_ctl->EMMC_REG_RESP_D1;
      cmd_done                    = ((rdat & 0x80000000) == ZERO)? 0 : 1;
    }

    // clear interrupt status
    emmc_ctl->EMMC_REG_INT_STATUS = SET_ALL_BITS;
  }
  while(!cmd_done);

  emmc_get_resp_data(handle);

  status = (det_err == ZERO)? SUCCESS : FAILURE;
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char emmc_cmd_all_send_cid(emmc_ctl_handle_t *handle)
{
  unsigned char status = FAILURE;
  unsigned int  rdat;
  unsigned int  cmd_arg;
  unsigned char cmd_done;
  unsigned char det_err;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  // clear interrupt status
  emmc_ctl->EMMC_REG_INT_STATUS = SET_ALL_BITS;

  emmc_ctl->EMMC_REG_CONFIG1 = 0;

  cmd_arg = 0;

  emmc_ctl->EMMC_REG_CTRL0 = 0;
  emmc_ctl->EMMC_REG_CTRL1 = cmd_arg;

  cmd_done  = 0;
  det_err   = 0;
  do
  {
    emmc_ctl->EMMC_REG_CTRL2      = (EMMC_CTRL2_START | EMMC_CMD_ALL_SEND_CID);
    wait_emmc_ctl_busy_status(handle,0);
    // read interrupt status, check that it is not due to timeout
    rdat                          = emmc_ctl->EMMC_REG_INT_STATUS;
    cmd_done                      = (GET_FIELD_VAL(rdat,EMMC_INT_CMD_TIMEOUT_IDX,2) == 0)? 1 : 0;
    det_err                       = ((rdat & 0xFFFFFFFE) == ZERO)? 0 : 1;

    // clear interrupt status
    emmc_ctl->EMMC_REG_INT_STATUS = SET_ALL_BITS;
  }
  while(!cmd_done);

  emmc_get_resp_data(handle);

  status = (det_err == ZERO)? SUCCESS : FAILURE;
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char emmc_cmd_set_relative_addr(emmc_ctl_handle_t *handle, unsigned int tgt_addr)
{
  unsigned char status = FAILURE;
  unsigned int  rdat;
  unsigned int  cmd_arg;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  emmc_ctl->EMMC_REG_CONFIG1 = 0;

  cmd_arg = tgt_addr;

  emmc_ctl->EMMC_REG_CTRL0 = 0;
  emmc_ctl->EMMC_REG_CTRL1 = cmd_arg;
  emmc_ctl->EMMC_REG_CTRL2 = (EMMC_CTRL2_START | EMMC_CMD_SET_RELATIVE_ADDR);

  wait_emmc_ctl_busy_status(handle,0);
  handle->tgt_addr         = tgt_addr;

  emmc_get_resp_data(handle);

  status = emmc_check_error_status(handle);
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char emmc_cmd_switch(emmc_ctl_handle_t *handle, unsigned int access,
                              unsigned int index, unsigned int value, unsigned int cmd_set)
{
  unsigned char status = FAILURE;
  unsigned int rdat;
  unsigned int cmd_arg;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  emmc_ctl->EMMC_REG_CONFIG1 = 0;

  cmd_arg = 0;
  SET_REG_FIELD(cmd_arg, access,  2, 24);
  SET_REG_FIELD(cmd_arg, index,   8, 16);
  SET_REG_FIELD(cmd_arg, value,   8, 8);
  SET_REG_FIELD(cmd_arg, cmd_set, 3, 0);

  emmc_ctl->EMMC_REG_CTRL0 = 0;
  emmc_ctl->EMMC_REG_CTRL1 = cmd_arg;
  emmc_ctl->EMMC_REG_CTRL2 = (EMMC_CTRL2_START | EMMC_CMD_SWITCH);

  wait_emmc_ctl_busy_status(handle,0);

  emmc_get_resp_data(handle);

  status = emmc_check_error_status(handle);
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char emmc_cmd_select_card(emmc_ctl_handle_t *handle)
{
  unsigned char status = FAILURE;
  unsigned int rdat;
  unsigned int cmd_arg;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  emmc_ctl->EMMC_REG_CONFIG1 = 0;

  cmd_arg = handle->tgt_addr;

  emmc_ctl->EMMC_REG_CTRL0 = 0;
  emmc_ctl->EMMC_REG_CTRL1 = cmd_arg;
  emmc_ctl->EMMC_REG_CTRL2 = (EMMC_CTRL2_START | EMMC_CMD_SELECT_CARD);

  wait_emmc_ctl_busy_status(handle,0);

  emmc_get_resp_data(handle);

  status = emmc_check_error_status(handle);
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char emmc_cmd_deselect_card(emmc_ctl_handle_t *handle)
{
  unsigned char status = FAILURE;
  unsigned int rdat;
  unsigned int cmd_arg;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  emmc_ctl->EMMC_REG_CONFIG1 = 0;

  cmd_arg = 0;

  emmc_ctl->EMMC_REG_CTRL0 = 0;
  emmc_ctl->EMMC_REG_CTRL1 = cmd_arg;
  emmc_ctl->EMMC_REG_CTRL2 = (EMMC_CTRL2_START | EMMC_CMD_SELECT_CARD);

  wait_emmc_ctl_busy_status(handle,0);

  emmc_get_resp_data(handle);

  status = emmc_check_error_status(handle);
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char emmc_cmd_send_ext_csd(emmc_ctl_handle_t *handle, unsigned int dst_addr)
{
  unsigned char status = FAILURE;
  unsigned char block_size;
  unsigned int rdat;
  unsigned int cmd_arg;
  unsigned int block_cfg;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  emmc_ctl->EMMC_REG_CONFIG1 = 0xFFFE0000;
  emmc_ctl->EMMC_REG_SRC_DST = dst_addr;  // memory address/location to put the return data

  cmd_arg     = 0;
  block_cfg   = 0;
  block_size  = get_block_size_encoding(handle->emmc_block_size);
  SET_REG_FIELD(block_cfg, block_size, 4, EMMC_CTRL0_BLOCK_LEN_IDX);  // block length
  SET_REG_FIELD(block_cfg, 1, 16, EMMC_CTRL0_NUM_BLOCKS_IDX);         // number of blocks = 1

  emmc_ctl->EMMC_REG_CTRL0 = block_cfg;
  emmc_ctl->EMMC_REG_CTRL1 = cmd_arg;
  emmc_ctl->EMMC_REG_CTRL2 = (EMMC_CTRL2_START | EMMC_CMD_SEND_EXT_CSD);

  wait_emmc_ctl_busy_status(handle,0);

  emmc_get_resp_data(handle);

  status = emmc_check_error_status(handle);
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char emmc_cmd_send_csd(emmc_ctl_handle_t *handle)
{
  unsigned char status = FAILURE;
  unsigned int  rdat;
  unsigned int  cmd_arg;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  emmc_ctl->EMMC_REG_CONFIG1 = 0xFFFE0000;

  cmd_arg = handle->tgt_addr;

  emmc_ctl->EMMC_REG_CTRL0 = 0;
  emmc_ctl->EMMC_REG_CTRL1 = cmd_arg;
  emmc_ctl->EMMC_REG_CTRL2 = (EMMC_CTRL2_START | EMMC_CMD_SEND_CSD);

  wait_emmc_ctl_busy_status(handle,0);

  emmc_get_resp_data(handle);

  status = emmc_check_error_status(handle);
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char emmc_cmd_send_cid(emmc_ctl_handle_t *handle)
{
  unsigned char status = FAILURE;
  unsigned int  rdat;
  unsigned int  cmd_arg;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  emmc_ctl->EMMC_REG_CONFIG1 = 0xFFFE0000;

  cmd_arg = handle->tgt_addr;

  emmc_ctl->EMMC_REG_CTRL0 = 0;
  emmc_ctl->EMMC_REG_CTRL1 = cmd_arg;
  emmc_ctl->EMMC_REG_CTRL2 = (EMMC_CTRL2_START | EMMC_CMD_SEND_CID);

  wait_emmc_ctl_busy_status(handle,0);

  emmc_get_resp_data(handle);

  status = emmc_check_error_status(handle);
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char emmc_cmd_stop_transmission(emmc_ctl_handle_t *handle)
{
  unsigned char status = FAILURE;
  unsigned int rdat;
  unsigned int cmd_arg;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  emmc_ctl->EMMC_REG_CONFIG1 = 0;

  cmd_arg = handle->tgt_addr;

  emmc_ctl->EMMC_REG_CTRL0 = 0;
  emmc_ctl->EMMC_REG_CTRL1 = cmd_arg;
  emmc_ctl->EMMC_REG_CTRL2 = (EMMC_CTRL2_START | EMMC_CMD_STOP_TRANSFER);

  wait_emmc_ctl_busy_status(handle,0);

  emmc_get_resp_data(handle);

  status = emmc_check_error_status(handle);
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char emmc_cmd_send_status(emmc_ctl_handle_t *handle)
{
  unsigned char status = FAILURE;
  unsigned int rdat;
  unsigned int cmd_arg;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  emmc_ctl->EMMC_REG_CONFIG1 = 0;

  cmd_arg = handle->tgt_addr;

  emmc_ctl->EMMC_REG_CTRL0 = 0;
  emmc_ctl->EMMC_REG_CTRL1 = cmd_arg;
  emmc_ctl->EMMC_REG_CTRL2 = (EMMC_CTRL2_START | EMMC_CMD_SEND_STATUS);

  wait_emmc_ctl_busy_status(handle,0);

  emmc_get_resp_data(handle);

  status = emmc_check_error_status(handle);
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char emmc_cmd_set_block_length(emmc_ctl_handle_t *handle, unsigned int blocklen)
{
  unsigned char status = FAILURE;
  unsigned int rdat;
  unsigned int cmd_arg;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  emmc_ctl->EMMC_REG_CONFIG1 = 0;

  cmd_arg = blocklen;

  emmc_ctl->EMMC_REG_CTRL0 = 0;
  emmc_ctl->EMMC_REG_CTRL1 = cmd_arg;
  emmc_ctl->EMMC_REG_CTRL2 = (EMMC_CTRL2_START | EMMC_CMD_SET_BLOCKLEN);

  wait_emmc_ctl_busy_status(handle,0);

  handle->emmc_block_size = blocklen;

  emmc_get_resp_data(handle);

  status = emmc_check_error_status(handle);
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char emmc_cmd_set_block_count(emmc_ctl_handle_t *handle, unsigned int blockcnt)
{
  unsigned char status = FAILURE;
  unsigned int rdat;
  unsigned int cmd_arg;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  emmc_ctl->EMMC_REG_CONFIG1 = 0;

  cmd_arg = blockcnt;

  emmc_ctl->EMMC_REG_CTRL0 = 0;
  emmc_ctl->EMMC_REG_CTRL1 = cmd_arg;
  emmc_ctl->EMMC_REG_CTRL2 = (EMMC_CTRL2_START | EMMC_CMD_SET_BLOCK_COUNT);

  wait_emmc_ctl_busy_status(handle,0);

  emmc_get_resp_data(handle);

  status = emmc_check_error_status(handle);
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char emmc_cmd_write_block(emmc_ctl_handle_t *handle, unsigned int src_addr)
{
  unsigned char status = FAILURE;
  unsigned char block_size;
  unsigned int rdat;
  unsigned int cmd_arg;
  unsigned int block_cfg;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  emmc_ctl->EMMC_REG_CONFIG1 = 0;
  emmc_ctl->EMMC_REG_SRC_DST = src_addr;  // memory address/location to fetch data

  cmd_arg     = handle->tgt_addr;
  block_cfg   = 0;
  block_size  = get_block_size_encoding(handle->emmc_block_size);
  SET_REG_FIELD(block_cfg, block_size, 4, EMMC_CTRL0_BLOCK_LEN_IDX);  // block length
  SET_REG_FIELD(block_cfg, 1, 16, EMMC_CTRL0_NUM_BLOCKS_IDX);         // number of blocks = 1

  emmc_ctl->EMMC_REG_CTRL0 = block_cfg;
  emmc_ctl->EMMC_REG_CTRL1 = cmd_arg;
  emmc_ctl->EMMC_REG_CTRL2 = (EMMC_CTRL2_START | EMMC_CMD_WR_BLOCK_ONE);

  wait_emmc_ctl_busy_status(handle,0);

  emmc_get_resp_data(handle);

  status = emmc_check_error_status(handle);
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char emmc_cmd_read_block(emmc_ctl_handle_t *handle, unsigned int dst_addr)
{
  unsigned char status = FAILURE;
  unsigned char block_size;
  unsigned int rdat;
  unsigned int cmd_arg;
  unsigned int block_cfg;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  emmc_ctl->EMMC_REG_CONFIG1 = 0xFFFE0000;
  emmc_ctl->EMMC_REG_SRC_DST = dst_addr;  // memory address/location to put the return data

  cmd_arg     = handle->tgt_addr;
  block_cfg   = 0;
  block_size  = get_block_size_encoding(handle->emmc_block_size);
  SET_REG_FIELD(block_cfg, block_size, 4, EMMC_CTRL0_BLOCK_LEN_IDX);  // block length
  SET_REG_FIELD(block_cfg, 1, 16, EMMC_CTRL0_NUM_BLOCKS_IDX);         // number of blocks = 1

  emmc_ctl->EMMC_REG_CTRL0 = block_cfg;
  emmc_ctl->EMMC_REG_CTRL1 = cmd_arg;
  emmc_ctl->EMMC_REG_CTRL2 = (EMMC_CTRL2_START | EMMC_CMD_RD_BLOCK_ONE);

  wait_emmc_ctl_busy_status(handle,0);

  emmc_get_resp_data(handle);

  status = emmc_check_error_status(handle);
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char emmc_cmd_bustest_w(emmc_ctl_handle_t *handle, unsigned int src_addr, unsigned int num_bytes)
{
  unsigned char status = FAILURE;
  unsigned char block_size;
  unsigned int rdat;
  unsigned int cmd_arg;
  unsigned int block_cfg;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  emmc_ctl->EMMC_REG_CONFIG1 = 0;
  emmc_ctl->EMMC_REG_SRC_DST = src_addr;  // memory address/location to fetch data

  cmd_arg     = 0;
  block_cfg   = 0;
  block_size  = get_block_size_encoding(num_bytes);
  SET_REG_FIELD(block_cfg, block_size, 4, EMMC_CTRL0_BLOCK_LEN_IDX);  // block length
  SET_REG_FIELD(block_cfg, 1, 16, EMMC_CTRL0_NUM_BLOCKS_IDX);         // number of blocks = 1

  emmc_ctl->EMMC_REG_CTRL0 = block_cfg;
  emmc_ctl->EMMC_REG_CTRL1 = cmd_arg;
  emmc_ctl->EMMC_REG_CTRL2 = (EMMC_CTRL2_START | EMMC_CMD_BUS_TEST_W);

  wait_emmc_ctl_busy_status(handle,0);

  emmc_get_resp_data(handle);

  status = emmc_check_error_status(handle);
  return status;
}

// ------------------------------------------------------------------------------------------------------------
unsigned char emmc_cmd_bustest_r(emmc_ctl_handle_t *handle, unsigned int dst_addr, unsigned int num_bytes)
{
  unsigned char status = FAILURE;
  unsigned char block_size;
  unsigned int rdat;
  unsigned int cmd_arg;
  unsigned int block_cfg;

  if (!handle)
    return FAILURE;

  if(handle->base_addr == ZERO)
    return FAILURE;

  emmc_ctl_reg_t *emmc_ctl=(emmc_ctl_reg_t *)(handle->base_addr);

  emmc_ctl->EMMC_REG_CONFIG1 = 0xFFFE0000;
  emmc_ctl->EMMC_REG_SRC_DST = dst_addr;  // memory address/location to put the return data

  cmd_arg     = 0;
  block_cfg   = 0;
  block_size  = get_block_size_encoding(num_bytes);
  SET_REG_FIELD(block_cfg, block_size, 4, EMMC_CTRL0_BLOCK_LEN_IDX);  // block length
  SET_REG_FIELD(block_cfg, 1, 16, EMMC_CTRL0_NUM_BLOCKS_IDX);         // number of blocks = 1

  emmc_ctl->EMMC_REG_CTRL0 = block_cfg;
  emmc_ctl->EMMC_REG_CTRL1 = cmd_arg;
  emmc_ctl->EMMC_REG_CTRL2 = (EMMC_CTRL2_START | EMMC_CMD_BUS_TEST_R);

  wait_emmc_ctl_busy_status(handle,0);

  emmc_get_resp_data(handle);

  status = emmc_check_error_status(handle);
  return status;
}


// ------------------------------------------------------------------------------------------------------------

