/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.1.0.2506031608
    Soft IP Version: 1.3.0
    2025 10 15 16:18:05
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module axi2apb0 (aclk_i, aresetn_i, apb_mas_addr_o, apb_mas_sel_o,
    apb_mas_en_o, apb_mas_write_o, apb_mas_wdata_o, apb_mas_ready_i,
    apb_mas_rdata_i, apb_mas_slverr_i, axi_slv_awvalid_i, axi_slv_awready_o,
    axi_slv_awaddr_i, axi_slv_awsize_i, axi_slv_awburst_i, axi_slv_awlock_i,
    axi_slv_awlen_i, axi_slv_awid_i, axi_slv_awprot_i, axi_slv_awcache_i,
    axi_slv_awqos_i, axi_slv_awregion_i, axi_slv_awuser_i, axi_slv_wvalid_i,
    axi_slv_wdata_i, axi_slv_wlast_i, axi_slv_wuser_i, axi_slv_wstrb_i,
    axi_slv_wready_o, axi_slv_bvalid_o, axi_slv_bready_i, axi_slv_bresp_o,
    axi_slv_buser_o, axi_slv_bid_o, axi_slv_arvalid_i, axi_slv_arready_o,
    axi_slv_araddr_i, axi_slv_arsize_i, axi_slv_arburst_i, axi_slv_arlock_i,
    axi_slv_arlen_i, axi_slv_arid_i, axi_slv_arprot_i, axi_slv_arcache_i,
    axi_slv_arqos_i, axi_slv_arregion_i, axi_slv_aruser_i, axi_slv_rvalid_o,
    axi_slv_rready_i, axi_slv_rdata_o, axi_slv_rlast_o, axi_slv_rresp_o,
    axi_slv_ruser_o, axi_slv_rid_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  aclk_i;
    input  aresetn_i;
    output  [31:0]  apb_mas_addr_o;
    output  [0:0]  apb_mas_sel_o;
    output  [0:0]  apb_mas_en_o;
    output  [0:0]  apb_mas_write_o;
    output  [31:0]  apb_mas_wdata_o;
    input  [0:0]  apb_mas_ready_i;
    input  [31:0]  apb_mas_rdata_i;
    input  [0:0]  apb_mas_slverr_i;
    input  [0:0]  axi_slv_awvalid_i;
    output  [0:0]  axi_slv_awready_o;
    input  [31:0]  axi_slv_awaddr_i;
    input  [2:0]  axi_slv_awsize_i;
    input  [1:0]  axi_slv_awburst_i;
    input  [0:0]  axi_slv_awlock_i;
    input  [7:0]  axi_slv_awlen_i;
    input  [3:0]  axi_slv_awid_i;
    input  [2:0]  axi_slv_awprot_i;
    input  [3:0]  axi_slv_awcache_i;
    input  [3:0]  axi_slv_awqos_i;
    input  [3:0]  axi_slv_awregion_i;
    input  [0:0]  axi_slv_awuser_i;
    input  [0:0]  axi_slv_wvalid_i;
    input  [31:0]  axi_slv_wdata_i;
    input  [0:0]  axi_slv_wlast_i;
    input  [0:0]  axi_slv_wuser_i;
    input  [3:0]  axi_slv_wstrb_i;
    output  [0:0]  axi_slv_wready_o;
    output  [0:0]  axi_slv_bvalid_o;
    input  [0:0]  axi_slv_bready_i;
    output  [1:0]  axi_slv_bresp_o;
    output  [0:0]  axi_slv_buser_o;
    output  [3:0]  axi_slv_bid_o;
    input  [0:0]  axi_slv_arvalid_i;
    output  [0:0]  axi_slv_arready_o;
    input  [31:0]  axi_slv_araddr_i;
    input  [2:0]  axi_slv_arsize_i;
    input  [1:0]  axi_slv_arburst_i;
    input  [0:0]  axi_slv_arlock_i;
    input  [7:0]  axi_slv_arlen_i;
    input  [3:0]  axi_slv_arid_i;
    input  [2:0]  axi_slv_arprot_i;
    input  [3:0]  axi_slv_arcache_i;
    input  [3:0]  axi_slv_arqos_i;
    input  [3:0]  axi_slv_arregion_i;
    input  [0:0]  axi_slv_aruser_i;
    output  [0:0]  axi_slv_rvalid_o;
    input  [0:0]  axi_slv_rready_i;
    output  [31:0]  axi_slv_rdata_o;
    output  [0:0]  axi_slv_rlast_o;
    output  [1:0]  axi_slv_rresp_o;
    output  [0:0]  axi_slv_ruser_o;
    output  [3:0]  axi_slv_rid_o;
endmodule