/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.1.0.2506031608
    Soft IP Version: 1.9.1
    2025 08 12 11:21:43
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module pll0 (clki_i, rstn_i, clkop_o, lock_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clki_i;
    input  rstn_i;
    output  clkop_o;
    output  lock_o;
endmodule