// >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
// ------------------------------------------------------------------
// Copyright (c) 2019-2025 by Lattice Semiconductor Corporation
// ALL RIGHTS RESERVED
// ------------------------------------------------------------------
//
// IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™
// DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.
//
// Lattice grants permission to use this code pursuant to the
// terms of the Lattice Propel License Agreement.
//
// DISCLAIMER:
//
//  LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS, WHETHER
//  EXPRESSED, IMPLIED, STATUTORY, OR IN ANY PROVISION OF THE LATTICE
//  PROPEL LICENSE AGREEMENT OR COMMUNICATION WITH LICENSEE, AND LATTICE
//  SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF MERCHANTABILITY OR
//  FITNESS FOR A PARTICULAR PURPOSE.  LATTICE DOES NOT WARRANT THAT THE
//  FUNCTIONS CONTAINED HEREIN WILL MEET LICENSEE'S REQUIREMENTS, OR THAT
//  LICENSEE'S OPERATION OF ANY DEVICE, SOFTWARE OR SYSTEM USING THIS FILE
//  OR ITS CONTENTS WILL BE UNINTERRUPTED OR ERROR FREE, OR THAT DEFECTS
//  HEREIN WILL BE CORRECTED.  LICENSEE ASSUMES RESPONSIBILITY FOR 
//  SELECTION OF MATERIALS TO ACHIEVE ITS INTENDED RESULTS, AND FOR THE
//  PROPER INSTALLATION, USE, AND RESULTS OBTAINED THEREFROM.  LICENSEE
//  ASSUMES THE ENTIRE RISK OF THE FILE AND ITS CONTENTS PROVING DEFECTIVE
//  OR FAILING TO PERFORM PROPERLY AND IN SUCH EVENT, LICENSEE SHALL
//  ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, SERVICE, CORRECTION, OR
//  ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR ASSOCIATED WITH THE
//  SOFTWARE.  IN NO EVENT SHALL LATTICE BE LIABLE TO ANY PARTY FOR DIRECT,
//  INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST
//  PROFITS, ARISING OUT OF THE USE OF THIS FILE OR ITS CONTENTS, EVEN IF
//  LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. LATTICE'S
//  SOLE LIABILITY, AND LICENSEE'S SOLE REMEDY, IS SET FORTH ABOVE. 
//  LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE, ITS CONTENTS OR
//  USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES' INTELLECTUAL PROPERTY
//  RIGHTS, INCLUDING ANY PATENT. IT IS THE USER'S RESPONSIBILITY TO VERIFY
//  THE USER SOFTWARE DESIGN FOR CONSISTENCY AND FUNCTIONALITY THROUGH THE
//  USE OF FORMAL SOFTWARE VALIDATION METHODS.
// ------------------------------------------------------------------

/* synthesis translate_off*/
`define SBP_SIMULATION
/* synthesis translate_on*/
`ifndef SBP_SIMULATION
`define SBP_SYNTHESIS
`endif



//
// Verific Verilog Description of module soc_emmc
//
module soc_emmc (emmc_dat_io, emmc_clk_o, emmc_cmd_io, emmc_rst_n_o, 
            rstn_i, uart0_rxd_i, uart0_txd_o);
    inout [7:0]emmc_dat_io;
    output emmc_clk_o;
    inout emmc_cmd_io;
    output emmc_rst_n_o;
    input rstn_i;
    input uart0_rxd_i;
    output uart0_txd_o;
    
    wire [31:0]apb_int0_inst_APB_M00_interconnect_PADDR;
    wire [31:0]apb_int0_inst_APB_M00_interconnect_PRDATA;
    wire [31:0]apb_int0_inst_APB_M00_interconnect_PWDATA;
    wire [31:0]apb_int0_inst_APB_M01_interconnect_PADDR;
    wire [31:0]apb_int0_inst_APB_M01_interconnect_PRDATA;
    wire [31:0]apb_int0_inst_APB_M01_interconnect_PWDATA;
    wire [31:0]axi2apb0_inst_APB3_M_interconnect_PADDR;
    wire [31:0]axi2apb0_inst_APB3_M_interconnect_PRDATA;
    wire [31:0]axi2apb0_inst_APB3_M_interconnect_PWDATA;
    
    wire apb_int0_inst_APB_M00_interconnect_PENABLE, apb_int0_inst_APB_M00_interconnect_PREADY, 
        apb_int0_inst_APB_M00_interconnect_PSELx, apb_int0_inst_APB_M00_interconnect_PSLVERR, 
        apb_int0_inst_APB_M00_interconnect_PWRITE, apb_int0_inst_APB_M01_interconnect_PENABLE, 
        apb_int0_inst_APB_M01_interconnect_PREADY, apb_int0_inst_APB_M01_interconnect_PSELx, 
        apb_int0_inst_APB_M01_interconnect_PSLVERR, apb_int0_inst_APB_M01_interconnect_PWRITE, 
        pll0_inst_clkop_o_net, cpu0_inst_system_resetn_o_net, axi2apb0_inst_APB3_M_interconnect_PENABLE, 
        axi2apb0_inst_APB3_M_interconnect_PREADY, axi2apb0_inst_APB3_M_interconnect_PSELx, 
        axi2apb0_inst_APB3_M_interconnect_PSLVERR, axi2apb0_inst_APB3_M_interconnect_PWRITE;
    wire [31:0]axi4_bus0_inst_AXI_M01_interconnect_ARADDR;
    wire [1:0]axi4_bus0_inst_AXI_M01_interconnect_ARBURST;
    wire [3:0]axi4_bus0_inst_AXI_M01_interconnect_ARCACHE;
    wire [3:0]axi4_bus0_inst_AXI_M01_interconnect_ARID;
    wire [7:0]axi4_bus0_inst_AXI_M01_interconnect_ARLEN;
    wire [2:0]axi4_bus0_inst_AXI_M01_interconnect_ARPROT;
    wire [3:0]axi4_bus0_inst_AXI_M01_interconnect_ARQOS;
    wire [3:0]axi4_bus0_inst_AXI_M01_interconnect_ARREGION;
    wire [2:0]axi4_bus0_inst_AXI_M01_interconnect_ARSIZE;
    wire [31:0]axi4_bus0_inst_AXI_M01_interconnect_AWADDR;
    wire [1:0]axi4_bus0_inst_AXI_M01_interconnect_AWBURST;
    wire [3:0]axi4_bus0_inst_AXI_M01_interconnect_AWCACHE;
    wire [3:0]axi4_bus0_inst_AXI_M01_interconnect_AWID;
    wire [7:0]axi4_bus0_inst_AXI_M01_interconnect_AWLEN;
    wire [2:0]axi4_bus0_inst_AXI_M01_interconnect_AWPROT;
    wire [3:0]axi4_bus0_inst_AXI_M01_interconnect_AWQOS;
    wire [3:0]axi4_bus0_inst_AXI_M01_interconnect_AWREGION;
    wire [2:0]axi4_bus0_inst_AXI_M01_interconnect_AWSIZE;
    wire [3:0]axi4_bus0_inst_AXI_M01_interconnect_BID;
    wire [1:0]axi4_bus0_inst_AXI_M01_interconnect_BRESP;
    wire [31:0]axi4_bus0_inst_AXI_M01_interconnect_RDATA;
    wire [3:0]axi4_bus0_inst_AXI_M01_interconnect_RID;
    wire [1:0]axi4_bus0_inst_AXI_M01_interconnect_RRESP;
    wire [31:0]axi4_bus0_inst_AXI_M01_interconnect_WDATA;
    wire [3:0]axi4_bus0_inst_AXI_M01_interconnect_WSTRB;
    
    wire axi4_bus0_inst_AXI_M01_interconnect_ARLOCK, axi4_bus0_inst_AXI_M01_interconnect_ARREADY, 
        axi4_bus0_inst_AXI_M01_interconnect_ARUSER, axi4_bus0_inst_AXI_M01_interconnect_ARVALID, 
        axi4_bus0_inst_AXI_M01_interconnect_AWLOCK, axi4_bus0_inst_AXI_M01_interconnect_AWREADY, 
        axi4_bus0_inst_AXI_M01_interconnect_AWUSER, axi4_bus0_inst_AXI_M01_interconnect_AWVALID, 
        axi4_bus0_inst_AXI_M01_interconnect_BREADY, axi4_bus0_inst_AXI_M01_interconnect_BUSER, 
        axi4_bus0_inst_AXI_M01_interconnect_BVALID, axi4_bus0_inst_AXI_M01_interconnect_RLAST, 
        axi4_bus0_inst_AXI_M01_interconnect_RREADY, axi4_bus0_inst_AXI_M01_interconnect_RUSER, 
        axi4_bus0_inst_AXI_M01_interconnect_RVALID, axi4_bus0_inst_AXI_M01_interconnect_WLAST, 
        axi4_bus0_inst_AXI_M01_interconnect_WREADY, axi4_bus0_inst_AXI_M01_interconnect_WUSER, 
        axi4_bus0_inst_AXI_M01_interconnect_WVALID;
    wire [31:0]axi4_bus0_inst_AXI_M00_interconnect_ARADDR;
    wire [1:0]axi4_bus0_inst_AXI_M00_interconnect_ARBURST;
    wire [3:0]axi4_bus0_inst_AXI_M00_interconnect_ARCACHE;
    wire [3:0]axi4_bus0_inst_AXI_M00_interconnect_ARID;
    wire [7:0]axi4_bus0_inst_AXI_M00_interconnect_ARLEN;
    wire [2:0]axi4_bus0_inst_AXI_M00_interconnect_ARPROT;
    wire [3:0]axi4_bus0_inst_AXI_M00_interconnect_ARQOS;
    wire [3:0]axi4_bus0_inst_AXI_M00_interconnect_ARREGION;
    wire [2:0]axi4_bus0_inst_AXI_M00_interconnect_ARSIZE;
    wire [31:0]axi4_bus0_inst_AXI_M00_interconnect_AWADDR;
    wire [1:0]axi4_bus0_inst_AXI_M00_interconnect_AWBURST;
    wire [3:0]axi4_bus0_inst_AXI_M00_interconnect_AWCACHE;
    wire [3:0]axi4_bus0_inst_AXI_M00_interconnect_AWID;
    wire [7:0]axi4_bus0_inst_AXI_M00_interconnect_AWLEN;
    wire [2:0]axi4_bus0_inst_AXI_M00_interconnect_AWPROT;
    wire [3:0]axi4_bus0_inst_AXI_M00_interconnect_AWQOS;
    wire [3:0]axi4_bus0_inst_AXI_M00_interconnect_AWREGION;
    wire [2:0]axi4_bus0_inst_AXI_M00_interconnect_AWSIZE;
    wire [3:0]axi4_bus0_inst_AXI_M00_interconnect_BID;
    wire [1:0]axi4_bus0_inst_AXI_M00_interconnect_BRESP;
    wire [31:0]axi4_bus0_inst_AXI_M00_interconnect_RDATA;
    wire [3:0]axi4_bus0_inst_AXI_M00_interconnect_RID;
    wire [1:0]axi4_bus0_inst_AXI_M00_interconnect_RRESP;
    wire [31:0]axi4_bus0_inst_AXI_M00_interconnect_WDATA;
    wire [3:0]axi4_bus0_inst_AXI_M00_interconnect_WSTRB;
    wire [31:0]cpu0_inst_AXI_M_DATA_interconnect_ARADDR;
    wire [1:0]cpu0_inst_AXI_M_DATA_interconnect_ARBURST;
    wire [3:0]cpu0_inst_AXI_M_DATA_interconnect_ARCACHE;
    wire [2:0]cpu0_inst_AXI_M_DATA_interconnect_ARID;
    wire [7:0]cpu0_inst_AXI_M_DATA_interconnect_ARLEN;
    wire [2:0]cpu0_inst_AXI_M_DATA_interconnect_ARPROT;
    wire [3:0]cpu0_inst_AXI_M_DATA_interconnect_ARQOS;
    wire [3:0]cpu0_inst_AXI_M_DATA_interconnect_ARREGION;
    wire [2:0]cpu0_inst_AXI_M_DATA_interconnect_ARSIZE;
    wire [31:0]cpu0_inst_AXI_M_DATA_interconnect_AWADDR;
    wire [1:0]cpu0_inst_AXI_M_DATA_interconnect_AWBURST;
    wire [3:0]cpu0_inst_AXI_M_DATA_interconnect_AWCACHE;
    wire [2:0]cpu0_inst_AXI_M_DATA_interconnect_AWID;
    wire [7:0]cpu0_inst_AXI_M_DATA_interconnect_AWLEN;
    wire [2:0]cpu0_inst_AXI_M_DATA_interconnect_AWPROT;
    wire [3:0]cpu0_inst_AXI_M_DATA_interconnect_AWQOS;
    wire [3:0]cpu0_inst_AXI_M_DATA_interconnect_AWREGION;
    wire [2:0]cpu0_inst_AXI_M_DATA_interconnect_AWSIZE;
    wire [2:0]cpu0_inst_AXI_M_DATA_interconnect_BID;
    wire [1:0]cpu0_inst_AXI_M_DATA_interconnect_BRESP;
    wire [31:0]cpu0_inst_AXI_M_DATA_interconnect_RDATA;
    wire [2:0]cpu0_inst_AXI_M_DATA_interconnect_RID;
    wire [1:0]cpu0_inst_AXI_M_DATA_interconnect_RRESP;
    wire [31:0]cpu0_inst_AXI_M_DATA_interconnect_WDATA;
    wire [3:0]cpu0_inst_AXI_M_DATA_interconnect_WSTRB;
    wire [31:0]emmc0_inst_AXI4_M0_interconnect_ARADDR;
    wire [1:0]emmc0_inst_AXI4_M0_interconnect_ARBURST;
    wire [2:0]emmc0_inst_AXI4_M0_interconnect_ARID;
    wire [7:0]emmc0_inst_AXI4_M0_interconnect_ARLEN;
    wire [2:0]emmc0_inst_AXI4_M0_interconnect_ARPROT;
    wire [2:0]emmc0_inst_AXI4_M0_interconnect_ARSIZE;
    wire [31:0]emmc0_inst_AXI4_M0_interconnect_AWADDR;
    wire [1:0]emmc0_inst_AXI4_M0_interconnect_AWBURST;
    wire [2:0]emmc0_inst_AXI4_M0_interconnect_AWID;
    wire [7:0]emmc0_inst_AXI4_M0_interconnect_AWLEN;
    wire [2:0]emmc0_inst_AXI4_M0_interconnect_AWPROT;
    wire [2:0]emmc0_inst_AXI4_M0_interconnect_AWSIZE;
    wire [2:0]emmc0_inst_AXI4_M0_interconnect_BID;
    wire [1:0]emmc0_inst_AXI4_M0_interconnect_BRESP;
    wire [31:0]emmc0_inst_AXI4_M0_interconnect_RDATA;
    wire [2:0]emmc0_inst_AXI4_M0_interconnect_RID;
    wire [1:0]emmc0_inst_AXI4_M0_interconnect_RRESP;
    wire [31:0]emmc0_inst_AXI4_M0_interconnect_WDATA;
    wire [3:0]emmc0_inst_AXI4_M0_interconnect_WSTRB;
    
    wire axi4_bus0_inst_AXI_M00_interconnect_ARLOCK, axi4_bus0_inst_AXI_M00_interconnect_ARREADY, 
        axi4_bus0_inst_AXI_M00_interconnect_ARVALID, axi4_bus0_inst_AXI_M00_interconnect_AWLOCK, 
        axi4_bus0_inst_AXI_M00_interconnect_AWREADY, axi4_bus0_inst_AXI_M00_interconnect_AWVALID, 
        axi4_bus0_inst_AXI_M00_interconnect_BREADY, axi4_bus0_inst_AXI_M00_interconnect_BVALID, 
        axi4_bus0_inst_AXI_M00_interconnect_RLAST, axi4_bus0_inst_AXI_M00_interconnect_RREADY, 
        axi4_bus0_inst_AXI_M00_interconnect_RVALID, axi4_bus0_inst_AXI_M00_interconnect_WLAST, 
        axi4_bus0_inst_AXI_M00_interconnect_WREADY, axi4_bus0_inst_AXI_M00_interconnect_WVALID, 
        cpu0_inst_AXI_M_DATA_interconnect_ARLOCK, cpu0_inst_AXI_M_DATA_interconnect_ARREADY, 
        cpu0_inst_AXI_M_DATA_interconnect_ARVALID, cpu0_inst_AXI_M_DATA_interconnect_AWLOCK, 
        cpu0_inst_AXI_M_DATA_interconnect_AWREADY, cpu0_inst_AXI_M_DATA_interconnect_AWVALID, 
        cpu0_inst_AXI_M_DATA_interconnect_BREADY, cpu0_inst_AXI_M_DATA_interconnect_BVALID, 
        cpu0_inst_AXI_M_DATA_interconnect_RLAST, cpu0_inst_AXI_M_DATA_interconnect_RREADY, 
        cpu0_inst_AXI_M_DATA_interconnect_RVALID, cpu0_inst_AXI_M_DATA_interconnect_WLAST, 
        cpu0_inst_AXI_M_DATA_interconnect_WREADY, cpu0_inst_AXI_M_DATA_interconnect_WVALID, 
        emmc0_inst_AXI4_M0_interconnect_ARREADY, emmc0_inst_AXI4_M0_interconnect_ARVALID, 
        emmc0_inst_AXI4_M0_interconnect_AWREADY, emmc0_inst_AXI4_M0_interconnect_AWVALID, 
        emmc0_inst_AXI4_M0_interconnect_BREADY, emmc0_inst_AXI4_M0_interconnect_BVALID, 
        emmc0_inst_AXI4_M0_interconnect_RLAST, emmc0_inst_AXI4_M0_interconnect_RREADY, 
        emmc0_inst_AXI4_M0_interconnect_RVALID, emmc0_inst_AXI4_M0_interconnect_WLAST, 
        emmc0_inst_AXI4_M0_interconnect_WREADY, emmc0_inst_AXI4_M0_interconnect_WVALID;
    wire [31:0]cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_address;
    wire [31:0]cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_data;
    wire [3:0]cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_mask;
    wire [2:0]cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_size;
    wire [31:0]cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_payload_fragment_address;
    wire [31:0]cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_data;
    wire [31:0]cpu0_inst_AXI_M_INSTR_interconnect_ARADDR;
    wire [1:0]cpu0_inst_AXI_M_INSTR_interconnect_ARBURST;
    wire [3:0]cpu0_inst_AXI_M_INSTR_interconnect_ARCACHE;
    wire [2:0]cpu0_inst_AXI_M_INSTR_interconnect_ARID;
    wire [7:0]cpu0_inst_AXI_M_INSTR_interconnect_ARLEN;
    wire [2:0]cpu0_inst_AXI_M_INSTR_interconnect_ARPROT;
    wire [3:0]cpu0_inst_AXI_M_INSTR_interconnect_ARQOS;
    wire [3:0]cpu0_inst_AXI_M_INSTR_interconnect_ARREGION;
    wire [2:0]cpu0_inst_AXI_M_INSTR_interconnect_ARSIZE;
    wire [31:0]cpu0_inst_AXI_M_INSTR_interconnect_AWADDR;
    wire [1:0]cpu0_inst_AXI_M_INSTR_interconnect_AWBURST;
    wire [3:0]cpu0_inst_AXI_M_INSTR_interconnect_AWCACHE;
    wire [2:0]cpu0_inst_AXI_M_INSTR_interconnect_AWID;
    wire [7:0]cpu0_inst_AXI_M_INSTR_interconnect_AWLEN;
    wire [2:0]cpu0_inst_AXI_M_INSTR_interconnect_AWPROT;
    wire [3:0]cpu0_inst_AXI_M_INSTR_interconnect_AWQOS;
    wire [3:0]cpu0_inst_AXI_M_INSTR_interconnect_AWREGION;
    wire [2:0]cpu0_inst_AXI_M_INSTR_interconnect_AWSIZE;
    wire [2:0]cpu0_inst_AXI_M_INSTR_interconnect_BID;
    wire [1:0]cpu0_inst_AXI_M_INSTR_interconnect_BRESP;
    wire [31:0]cpu0_inst_AXI_M_INSTR_interconnect_RDATA;
    wire [2:0]cpu0_inst_AXI_M_INSTR_interconnect_RID;
    wire [1:0]cpu0_inst_AXI_M_INSTR_interconnect_RRESP;
    wire [31:0]cpu0_inst_AXI_M_INSTR_interconnect_WDATA;
    wire [3:0]cpu0_inst_AXI_M_INSTR_interconnect_WSTRB;
    wire [31:0]cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_address;
    wire [31:0]cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_data;
    wire [3:0]cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_mask;
    wire [2:0]cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_size;
    wire [31:0]cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_payload_data;
    
    wire osc0_inst_lf_clk_out_o_net, cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_payload_fragment_hit, 
        cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_payload_last, cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_ready, 
        cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_valid, cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_exclusive, 
        cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_last, cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_uncached, 
        cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_wr, cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_ready, 
        cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_valid, cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_payload_fragment_enable, 
        cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_payload_last, cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_ready, 
        cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_valid, cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_error, 
        cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_exclusive, cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_last, 
        cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_valid, cpu0_inst_AXI_M_INSTR_interconnect_ARLOCK, 
        cpu0_inst_AXI_M_INSTR_interconnect_ARREADY, cpu0_inst_AXI_M_INSTR_interconnect_ARVALID, 
        cpu0_inst_AXI_M_INSTR_interconnect_AWLOCK, cpu0_inst_AXI_M_INSTR_interconnect_AWREADY, 
        cpu0_inst_AXI_M_INSTR_interconnect_AWVALID, cpu0_inst_AXI_M_INSTR_interconnect_BREADY, 
        cpu0_inst_AXI_M_INSTR_interconnect_BVALID, cpu0_inst_AXI_M_INSTR_interconnect_RLAST, 
        cpu0_inst_AXI_M_INSTR_interconnect_RREADY, cpu0_inst_AXI_M_INSTR_interconnect_RVALID, 
        cpu0_inst_AXI_M_INSTR_interconnect_WLAST, cpu0_inst_AXI_M_INSTR_interconnect_WREADY, 
        cpu0_inst_AXI_M_INSTR_interconnect_WVALID, cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_last, 
        cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_uncached, cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_wr, 
        cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_ready, cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_valid, 
        cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_payload_error, cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_payload_last, 
        cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_valid, emmc0_inst_INTR_interconnect_IRQ, 
        uart0_inst_INT_M0_interconnect_IRQ, equation_module_inst_O_net, 
        osc0_inst_hf_clk_out_o_net, pll0_inst_lock_o_net;
    
    
    assign equation_module_inst_O_net = (rstn_i & pll0_inst_lock_o_net) ; 

    apb_int0 apb_int0_inst (.apb_m00_paddr_mstr_o({apb_int0_inst_APB_M00_interconnect_PADDR}), 
            .apb_m00_prdata_mstr_i({apb_int0_inst_APB_M00_interconnect_PRDATA}), 
            .apb_m00_pwdata_mstr_o({apb_int0_inst_APB_M00_interconnect_PWDATA}), 
            .apb_m01_paddr_mstr_o({apb_int0_inst_APB_M01_interconnect_PADDR}), 
            .apb_m01_prdata_mstr_i({apb_int0_inst_APB_M01_interconnect_PRDATA}), 
            .apb_m01_pwdata_mstr_o({apb_int0_inst_APB_M01_interconnect_PWDATA}), 
            .apb_s00_paddr_slv_i({axi2apb0_inst_APB3_M_interconnect_PADDR}), 
            .apb_s00_prdata_slv_o({axi2apb0_inst_APB3_M_interconnect_PRDATA}), 
            .apb_s00_pwdata_slv_i({axi2apb0_inst_APB3_M_interconnect_PWDATA}), 
            .apb_m00_penable_mstr_o(apb_int0_inst_APB_M00_interconnect_PENABLE), 
            .apb_m00_pready_mstr_i(apb_int0_inst_APB_M00_interconnect_PREADY), 
            .apb_m00_psel_mstr_o(apb_int0_inst_APB_M00_interconnect_PSELx), 
            .apb_m00_pslverr_mstr_i(apb_int0_inst_APB_M00_interconnect_PSLVERR), 
            .apb_m00_pwrite_mstr_o(apb_int0_inst_APB_M00_interconnect_PWRITE), 
            .apb_m01_penable_mstr_o(apb_int0_inst_APB_M01_interconnect_PENABLE), 
            .apb_m01_pready_mstr_i(apb_int0_inst_APB_M01_interconnect_PREADY), 
            .apb_m01_psel_mstr_o(apb_int0_inst_APB_M01_interconnect_PSELx), 
            .apb_m01_pslverr_mstr_i(apb_int0_inst_APB_M01_interconnect_PSLVERR), 
            .apb_m01_pwrite_mstr_o(apb_int0_inst_APB_M01_interconnect_PWRITE), 
            .apb_pclk_i(pll0_inst_clkop_o_net), .apb_presetn_i(cpu0_inst_system_resetn_o_net), 
            .apb_s00_penable_slv_i(axi2apb0_inst_APB3_M_interconnect_PENABLE), 
            .apb_s00_pready_slv_o(axi2apb0_inst_APB3_M_interconnect_PREADY), 
            .apb_s00_psel_slv_i(axi2apb0_inst_APB3_M_interconnect_PSELx), 
            .apb_s00_pslverr_slv_o(axi2apb0_inst_APB3_M_interconnect_PSLVERR), 
            .apb_s00_pwrite_slv_i(axi2apb0_inst_APB3_M_interconnect_PWRITE));
    defparam apb_int0_inst.FULL_DECODE_EN = 1;
    defparam apb_int0_inst.S0_ADDR_RANGE = 32'h00001000;
    defparam apb_int0_inst.S0_BASE_ADDR = 32'h40000000;
    defparam apb_int0_inst.S1_ADDR_RANGE = 32'h00001000;
    defparam apb_int0_inst.S1_BASE_ADDR = 32'h40001000;
    axi2apb0 axi2apb0_inst (.apb_mas_addr_o({axi2apb0_inst_APB3_M_interconnect_PADDR}), 
            .apb_mas_rdata_i({axi2apb0_inst_APB3_M_interconnect_PRDATA}), 
            .apb_mas_wdata_o({axi2apb0_inst_APB3_M_interconnect_PWDATA}), 
            .axi_slv_araddr_i({axi4_bus0_inst_AXI_M01_interconnect_ARADDR}), 
            .axi_slv_arburst_i({axi4_bus0_inst_AXI_M01_interconnect_ARBURST}), 
            .axi_slv_arcache_i({axi4_bus0_inst_AXI_M01_interconnect_ARCACHE}), 
            .axi_slv_arid_i({axi4_bus0_inst_AXI_M01_interconnect_ARID}), .axi_slv_arlen_i({axi4_bus0_inst_AXI_M01_interconnect_ARLEN}), 
            .axi_slv_arprot_i({axi4_bus0_inst_AXI_M01_interconnect_ARPROT}), 
            .axi_slv_arqos_i({axi4_bus0_inst_AXI_M01_interconnect_ARQOS}), 
            .axi_slv_arregion_i({axi4_bus0_inst_AXI_M01_interconnect_ARREGION}), 
            .axi_slv_arsize_i({axi4_bus0_inst_AXI_M01_interconnect_ARSIZE}), 
            .axi_slv_awaddr_i({axi4_bus0_inst_AXI_M01_interconnect_AWADDR}), 
            .axi_slv_awburst_i({axi4_bus0_inst_AXI_M01_interconnect_AWBURST}), 
            .axi_slv_awcache_i({axi4_bus0_inst_AXI_M01_interconnect_AWCACHE}), 
            .axi_slv_awid_i({axi4_bus0_inst_AXI_M01_interconnect_AWID}), .axi_slv_awlen_i({axi4_bus0_inst_AXI_M01_interconnect_AWLEN}), 
            .axi_slv_awprot_i({axi4_bus0_inst_AXI_M01_interconnect_AWPROT}), 
            .axi_slv_awqos_i({axi4_bus0_inst_AXI_M01_interconnect_AWQOS}), 
            .axi_slv_awregion_i({axi4_bus0_inst_AXI_M01_interconnect_AWREGION}), 
            .axi_slv_awsize_i({axi4_bus0_inst_AXI_M01_interconnect_AWSIZE}), 
            .axi_slv_bid_o({axi4_bus0_inst_AXI_M01_interconnect_BID}), .axi_slv_bresp_o({axi4_bus0_inst_AXI_M01_interconnect_BRESP}), 
            .axi_slv_rdata_o({axi4_bus0_inst_AXI_M01_interconnect_RDATA}), 
            .axi_slv_rid_o({axi4_bus0_inst_AXI_M01_interconnect_RID}), .axi_slv_rresp_o({axi4_bus0_inst_AXI_M01_interconnect_RRESP}), 
            .axi_slv_wdata_i({axi4_bus0_inst_AXI_M01_interconnect_WDATA}), 
            .axi_slv_wstrb_i({axi4_bus0_inst_AXI_M01_interconnect_WSTRB}), 
            .aclk_i(pll0_inst_clkop_o_net), .apb_mas_en_o(axi2apb0_inst_APB3_M_interconnect_PENABLE), 
            .apb_mas_ready_i(axi2apb0_inst_APB3_M_interconnect_PREADY), .apb_mas_sel_o(axi2apb0_inst_APB3_M_interconnect_PSELx), 
            .apb_mas_slverr_i(axi2apb0_inst_APB3_M_interconnect_PSLVERR), 
            .apb_mas_write_o(axi2apb0_inst_APB3_M_interconnect_PWRITE), .aresetn_i(cpu0_inst_system_resetn_o_net), 
            .axi_slv_arlock_i(axi4_bus0_inst_AXI_M01_interconnect_ARLOCK), 
            .axi_slv_arready_o(axi4_bus0_inst_AXI_M01_interconnect_ARREADY), 
            .axi_slv_aruser_i(axi4_bus0_inst_AXI_M01_interconnect_ARUSER), 
            .axi_slv_arvalid_i(axi4_bus0_inst_AXI_M01_interconnect_ARVALID), 
            .axi_slv_awlock_i(axi4_bus0_inst_AXI_M01_interconnect_AWLOCK), 
            .axi_slv_awready_o(axi4_bus0_inst_AXI_M01_interconnect_AWREADY), 
            .axi_slv_awuser_i(axi4_bus0_inst_AXI_M01_interconnect_AWUSER), 
            .axi_slv_awvalid_i(axi4_bus0_inst_AXI_M01_interconnect_AWVALID), 
            .axi_slv_bready_i(axi4_bus0_inst_AXI_M01_interconnect_BREADY), 
            .axi_slv_buser_o(axi4_bus0_inst_AXI_M01_interconnect_BUSER), .axi_slv_bvalid_o(axi4_bus0_inst_AXI_M01_interconnect_BVALID), 
            .axi_slv_rlast_o(axi4_bus0_inst_AXI_M01_interconnect_RLAST), .axi_slv_rready_i(axi4_bus0_inst_AXI_M01_interconnect_RREADY), 
            .axi_slv_ruser_o(axi4_bus0_inst_AXI_M01_interconnect_RUSER), .axi_slv_rvalid_o(axi4_bus0_inst_AXI_M01_interconnect_RVALID), 
            .axi_slv_wlast_i(axi4_bus0_inst_AXI_M01_interconnect_WLAST), .axi_slv_wready_o(axi4_bus0_inst_AXI_M01_interconnect_WREADY), 
            .axi_slv_wuser_i(axi4_bus0_inst_AXI_M01_interconnect_WUSER), .axi_slv_wvalid_i(axi4_bus0_inst_AXI_M01_interconnect_WVALID));
    axi4_bus0 axi4_bus0_inst (.axi_M00_araddr_o({axi4_bus0_inst_AXI_M00_interconnect_ARADDR}), 
            .axi_M00_arburst_o({axi4_bus0_inst_AXI_M00_interconnect_ARBURST}), 
            .axi_M00_arcache_o({axi4_bus0_inst_AXI_M00_interconnect_ARCACHE}), 
            .axi_M00_arid_o({axi4_bus0_inst_AXI_M00_interconnect_ARID}), .axi_M00_arlen_o({axi4_bus0_inst_AXI_M00_interconnect_ARLEN}), 
            .axi_M00_arprot_o({axi4_bus0_inst_AXI_M00_interconnect_ARPROT}), 
            .axi_M00_arqos_o({axi4_bus0_inst_AXI_M00_interconnect_ARQOS}), 
            .axi_M00_arregion_o({axi4_bus0_inst_AXI_M00_interconnect_ARREGION}), 
            .axi_M00_arsize_o({axi4_bus0_inst_AXI_M00_interconnect_ARSIZE}), 
            .axi_M00_awaddr_o({axi4_bus0_inst_AXI_M00_interconnect_AWADDR}), 
            .axi_M00_awburst_o({axi4_bus0_inst_AXI_M00_interconnect_AWBURST}), 
            .axi_M00_awcache_o({axi4_bus0_inst_AXI_M00_interconnect_AWCACHE}), 
            .axi_M00_awid_o({axi4_bus0_inst_AXI_M00_interconnect_AWID}), .axi_M00_awlen_o({axi4_bus0_inst_AXI_M00_interconnect_AWLEN}), 
            .axi_M00_awprot_o({axi4_bus0_inst_AXI_M00_interconnect_AWPROT}), 
            .axi_M00_awqos_o({axi4_bus0_inst_AXI_M00_interconnect_AWQOS}), 
            .axi_M00_awregion_o({axi4_bus0_inst_AXI_M00_interconnect_AWREGION}), 
            .axi_M00_awsize_o({axi4_bus0_inst_AXI_M00_interconnect_AWSIZE}), 
            .axi_M00_bid_i({axi4_bus0_inst_AXI_M00_interconnect_BID}), .axi_M00_bresp_i({axi4_bus0_inst_AXI_M00_interconnect_BRESP}), 
            .axi_M00_rdata_i({axi4_bus0_inst_AXI_M00_interconnect_RDATA}), 
            .axi_M00_rid_i({axi4_bus0_inst_AXI_M00_interconnect_RID}), .axi_M00_rresp_i({axi4_bus0_inst_AXI_M00_interconnect_RRESP}), 
            .axi_M00_wdata_o({axi4_bus0_inst_AXI_M00_interconnect_WDATA}), 
            .axi_M00_wstrb_o({axi4_bus0_inst_AXI_M00_interconnect_WSTRB}), 
            .axi_M01_araddr_o({axi4_bus0_inst_AXI_M01_interconnect_ARADDR}), 
            .axi_M01_arburst_o({axi4_bus0_inst_AXI_M01_interconnect_ARBURST}), 
            .axi_M01_arcache_o({axi4_bus0_inst_AXI_M01_interconnect_ARCACHE}), 
            .axi_M01_arid_o({axi4_bus0_inst_AXI_M01_interconnect_ARID}), .axi_M01_arlen_o({axi4_bus0_inst_AXI_M01_interconnect_ARLEN}), 
            .axi_M01_arprot_o({axi4_bus0_inst_AXI_M01_interconnect_ARPROT}), 
            .axi_M01_arqos_o({axi4_bus0_inst_AXI_M01_interconnect_ARQOS}), 
            .axi_M01_arregion_o({axi4_bus0_inst_AXI_M01_interconnect_ARREGION}), 
            .axi_M01_arsize_o({axi4_bus0_inst_AXI_M01_interconnect_ARSIZE}), 
            .axi_M01_awaddr_o({axi4_bus0_inst_AXI_M01_interconnect_AWADDR}), 
            .axi_M01_awburst_o({axi4_bus0_inst_AXI_M01_interconnect_AWBURST}), 
            .axi_M01_awcache_o({axi4_bus0_inst_AXI_M01_interconnect_AWCACHE}), 
            .axi_M01_awid_o({axi4_bus0_inst_AXI_M01_interconnect_AWID}), .axi_M01_awlen_o({axi4_bus0_inst_AXI_M01_interconnect_AWLEN}), 
            .axi_M01_awprot_o({axi4_bus0_inst_AXI_M01_interconnect_AWPROT}), 
            .axi_M01_awqos_o({axi4_bus0_inst_AXI_M01_interconnect_AWQOS}), 
            .axi_M01_awregion_o({axi4_bus0_inst_AXI_M01_interconnect_AWREGION}), 
            .axi_M01_awsize_o({axi4_bus0_inst_AXI_M01_interconnect_AWSIZE}), 
            .axi_M01_bid_i({axi4_bus0_inst_AXI_M01_interconnect_BID}), .axi_M01_bresp_i({axi4_bus0_inst_AXI_M01_interconnect_BRESP}), 
            .axi_M01_rdata_i({axi4_bus0_inst_AXI_M01_interconnect_RDATA}), 
            .axi_M01_rid_i({axi4_bus0_inst_AXI_M01_interconnect_RID}), .axi_M01_rresp_i({axi4_bus0_inst_AXI_M01_interconnect_RRESP}), 
            .axi_M01_wdata_o({axi4_bus0_inst_AXI_M01_interconnect_WDATA}), 
            .axi_M01_wstrb_o({axi4_bus0_inst_AXI_M01_interconnect_WSTRB}), 
            .axi_S00_araddr_i({cpu0_inst_AXI_M_DATA_interconnect_ARADDR}), 
            .axi_S00_arburst_i({cpu0_inst_AXI_M_DATA_interconnect_ARBURST}), 
            .axi_S00_arcache_i({cpu0_inst_AXI_M_DATA_interconnect_ARCACHE}), 
            .axi_S00_arid_i({cpu0_inst_AXI_M_DATA_interconnect_ARID}), .axi_S00_arlen_i({cpu0_inst_AXI_M_DATA_interconnect_ARLEN}), 
            .axi_S00_arprot_i({cpu0_inst_AXI_M_DATA_interconnect_ARPROT}), 
            .axi_S00_arqos_i({cpu0_inst_AXI_M_DATA_interconnect_ARQOS}), .axi_S00_arregion_i({cpu0_inst_AXI_M_DATA_interconnect_ARREGION}), 
            .axi_S00_arsize_i({cpu0_inst_AXI_M_DATA_interconnect_ARSIZE}), 
            .axi_S00_awaddr_i({cpu0_inst_AXI_M_DATA_interconnect_AWADDR}), 
            .axi_S00_awburst_i({cpu0_inst_AXI_M_DATA_interconnect_AWBURST}), 
            .axi_S00_awcache_i({cpu0_inst_AXI_M_DATA_interconnect_AWCACHE}), 
            .axi_S00_awid_i({cpu0_inst_AXI_M_DATA_interconnect_AWID}), .axi_S00_awlen_i({cpu0_inst_AXI_M_DATA_interconnect_AWLEN}), 
            .axi_S00_awprot_i({cpu0_inst_AXI_M_DATA_interconnect_AWPROT}), 
            .axi_S00_awqos_i({cpu0_inst_AXI_M_DATA_interconnect_AWQOS}), .axi_S00_awregion_i({cpu0_inst_AXI_M_DATA_interconnect_AWREGION}), 
            .axi_S00_awsize_i({cpu0_inst_AXI_M_DATA_interconnect_AWSIZE}), 
            .axi_S00_bid_o({cpu0_inst_AXI_M_DATA_interconnect_BID}), .axi_S00_bresp_o({cpu0_inst_AXI_M_DATA_interconnect_BRESP}), 
            .axi_S00_rdata_o({cpu0_inst_AXI_M_DATA_interconnect_RDATA}), .axi_S00_rid_o({cpu0_inst_AXI_M_DATA_interconnect_RID}), 
            .axi_S00_rresp_o({cpu0_inst_AXI_M_DATA_interconnect_RRESP}), .axi_S00_wdata_i({cpu0_inst_AXI_M_DATA_interconnect_WDATA}), 
            .axi_S00_wstrb_i({cpu0_inst_AXI_M_DATA_interconnect_WSTRB}), .axi_S01_araddr_i({emmc0_inst_AXI4_M0_interconnect_ARADDR}), 
            .axi_S01_arburst_i({emmc0_inst_AXI4_M0_interconnect_ARBURST}), 
            .axi_S01_arcache_i({4'b0000}), .axi_S01_arid_i({emmc0_inst_AXI4_M0_interconnect_ARID}), 
            .axi_S01_arlen_i({emmc0_inst_AXI4_M0_interconnect_ARLEN}), .axi_S01_arprot_i({emmc0_inst_AXI4_M0_interconnect_ARPROT}), 
            .axi_S01_arqos_i({4'b0000}), .axi_S01_arregion_i({4'b0000}), 
            .axi_S01_arsize_i({emmc0_inst_AXI4_M0_interconnect_ARSIZE}), .axi_S01_awaddr_i({emmc0_inst_AXI4_M0_interconnect_AWADDR}), 
            .axi_S01_awburst_i({emmc0_inst_AXI4_M0_interconnect_AWBURST}), 
            .axi_S01_awcache_i({4'b0000}), .axi_S01_awid_i({emmc0_inst_AXI4_M0_interconnect_AWID}), 
            .axi_S01_awlen_i({emmc0_inst_AXI4_M0_interconnect_AWLEN}), .axi_S01_awprot_i({emmc0_inst_AXI4_M0_interconnect_AWPROT}), 
            .axi_S01_awqos_i({4'b0000}), .axi_S01_awregion_i({4'b0000}), 
            .axi_S01_awsize_i({emmc0_inst_AXI4_M0_interconnect_AWSIZE}), .axi_S01_bid_o({emmc0_inst_AXI4_M0_interconnect_BID}), 
            .axi_S01_bresp_o({emmc0_inst_AXI4_M0_interconnect_BRESP}), .axi_S01_rdata_o({emmc0_inst_AXI4_M0_interconnect_RDATA}), 
            .axi_S01_rid_o({emmc0_inst_AXI4_M0_interconnect_RID}), .axi_S01_rresp_o({emmc0_inst_AXI4_M0_interconnect_RRESP}), 
            .axi_S01_wdata_i({emmc0_inst_AXI4_M0_interconnect_WDATA}), .axi_S01_wstrb_i({emmc0_inst_AXI4_M0_interconnect_WSTRB}), 
            .axi_M00_arlock_o(axi4_bus0_inst_AXI_M00_interconnect_ARLOCK), 
            .axi_M00_arready_i(axi4_bus0_inst_AXI_M00_interconnect_ARREADY), 
            .axi_M00_arvalid_o(axi4_bus0_inst_AXI_M00_interconnect_ARVALID), 
            .axi_M00_awlock_o(axi4_bus0_inst_AXI_M00_interconnect_AWLOCK), 
            .axi_M00_awready_i(axi4_bus0_inst_AXI_M00_interconnect_AWREADY), 
            .axi_M00_awvalid_o(axi4_bus0_inst_AXI_M00_interconnect_AWVALID), 
            .axi_M00_bready_o(axi4_bus0_inst_AXI_M00_interconnect_BREADY), 
            .axi_M00_buser_i(1'b0), .axi_M00_bvalid_i(axi4_bus0_inst_AXI_M00_interconnect_BVALID), 
            .axi_M00_rlast_i(axi4_bus0_inst_AXI_M00_interconnect_RLAST), .axi_M00_rready_o(axi4_bus0_inst_AXI_M00_interconnect_RREADY), 
            .axi_M00_ruser_i(1'b0), .axi_M00_rvalid_i(axi4_bus0_inst_AXI_M00_interconnect_RVALID), 
            .axi_M00_wlast_o(axi4_bus0_inst_AXI_M00_interconnect_WLAST), .axi_M00_wready_i(axi4_bus0_inst_AXI_M00_interconnect_WREADY), 
            .axi_M00_wvalid_o(axi4_bus0_inst_AXI_M00_interconnect_WVALID), 
            .axi_M01_arlock_o(axi4_bus0_inst_AXI_M01_interconnect_ARLOCK), 
            .axi_M01_arready_i(axi4_bus0_inst_AXI_M01_interconnect_ARREADY), 
            .axi_M01_aruser_o(axi4_bus0_inst_AXI_M01_interconnect_ARUSER), 
            .axi_M01_arvalid_o(axi4_bus0_inst_AXI_M01_interconnect_ARVALID), 
            .axi_M01_awlock_o(axi4_bus0_inst_AXI_M01_interconnect_AWLOCK), 
            .axi_M01_awready_i(axi4_bus0_inst_AXI_M01_interconnect_AWREADY), 
            .axi_M01_awuser_o(axi4_bus0_inst_AXI_M01_interconnect_AWUSER), 
            .axi_M01_awvalid_o(axi4_bus0_inst_AXI_M01_interconnect_AWVALID), 
            .axi_M01_bready_o(axi4_bus0_inst_AXI_M01_interconnect_BREADY), 
            .axi_M01_buser_i(axi4_bus0_inst_AXI_M01_interconnect_BUSER), .axi_M01_bvalid_i(axi4_bus0_inst_AXI_M01_interconnect_BVALID), 
            .axi_M01_rlast_i(axi4_bus0_inst_AXI_M01_interconnect_RLAST), .axi_M01_rready_o(axi4_bus0_inst_AXI_M01_interconnect_RREADY), 
            .axi_M01_ruser_i(axi4_bus0_inst_AXI_M01_interconnect_RUSER), .axi_M01_rvalid_i(axi4_bus0_inst_AXI_M01_interconnect_RVALID), 
            .axi_M01_wlast_o(axi4_bus0_inst_AXI_M01_interconnect_WLAST), .axi_M01_wready_i(axi4_bus0_inst_AXI_M01_interconnect_WREADY), 
            .axi_M01_wuser_o(axi4_bus0_inst_AXI_M01_interconnect_WUSER), .axi_M01_wvalid_o(axi4_bus0_inst_AXI_M01_interconnect_WVALID), 
            .axi_S00_arlock_i(cpu0_inst_AXI_M_DATA_interconnect_ARLOCK), .axi_S00_arready_o(cpu0_inst_AXI_M_DATA_interconnect_ARREADY), 
            .axi_S00_aruser_i(1'b0), .axi_S00_arvalid_i(cpu0_inst_AXI_M_DATA_interconnect_ARVALID), 
            .axi_S00_awlock_i(cpu0_inst_AXI_M_DATA_interconnect_AWLOCK), .axi_S00_awready_o(cpu0_inst_AXI_M_DATA_interconnect_AWREADY), 
            .axi_S00_awuser_i(1'b0), .axi_S00_awvalid_i(cpu0_inst_AXI_M_DATA_interconnect_AWVALID), 
            .axi_S00_bready_i(cpu0_inst_AXI_M_DATA_interconnect_BREADY), .axi_S00_bvalid_o(cpu0_inst_AXI_M_DATA_interconnect_BVALID), 
            .axi_S00_rlast_o(cpu0_inst_AXI_M_DATA_interconnect_RLAST), .axi_S00_rready_i(cpu0_inst_AXI_M_DATA_interconnect_RREADY), 
            .axi_S00_rvalid_o(cpu0_inst_AXI_M_DATA_interconnect_RVALID), .axi_S00_wlast_i(cpu0_inst_AXI_M_DATA_interconnect_WLAST), 
            .axi_S00_wready_o(cpu0_inst_AXI_M_DATA_interconnect_WREADY), .axi_S00_wuser_i(1'b0), 
            .axi_S00_wvalid_i(cpu0_inst_AXI_M_DATA_interconnect_WVALID), .axi_S01_arlock_i(1'b0), 
            .axi_S01_arready_o(emmc0_inst_AXI4_M0_interconnect_ARREADY), .axi_S01_aruser_i(1'b0), 
            .axi_S01_arvalid_i(emmc0_inst_AXI4_M0_interconnect_ARVALID), .axi_S01_awlock_i(1'b0), 
            .axi_S01_awready_o(emmc0_inst_AXI4_M0_interconnect_AWREADY), .axi_S01_awuser_i(1'b0), 
            .axi_S01_awvalid_i(emmc0_inst_AXI4_M0_interconnect_AWVALID), .axi_S01_bready_i(emmc0_inst_AXI4_M0_interconnect_BREADY), 
            .axi_S01_bvalid_o(emmc0_inst_AXI4_M0_interconnect_BVALID), .axi_S01_rlast_o(emmc0_inst_AXI4_M0_interconnect_RLAST), 
            .axi_S01_rready_i(emmc0_inst_AXI4_M0_interconnect_RREADY), .axi_S01_rvalid_o(emmc0_inst_AXI4_M0_interconnect_RVALID), 
            .axi_S01_wlast_i(emmc0_inst_AXI4_M0_interconnect_WLAST), .axi_S01_wready_o(emmc0_inst_AXI4_M0_interconnect_WREADY), 
            .axi_S01_wuser_i(1'b0), .axi_S01_wvalid_i(emmc0_inst_AXI4_M0_interconnect_WVALID), 
            .axi_aclk_i(pll0_inst_clkop_o_net), .axi_aresetn_i(cpu0_inst_system_resetn_o_net));
    defparam axi4_bus0_inst.EXT_MAS_AXI_ADDR_WIDTH = {7'd32,7'd32};
    defparam axi4_bus0_inst.EXT_SLV_AXI_ADDR_WIDTH = {7'd32,7'd32};
    defparam axi4_bus0_inst.EXT_SLV_FRAGMENT_BASE_ADDR = {64'h40001000,64'h40000000,64'h0000000000000000,64'h00200000};
    defparam axi4_bus0_inst.EXT_SLV_FRAGMENT_CNT = {5'd2,5'd1};
    defparam axi4_bus0_inst.EXT_SLV_FRAGMENT_END_ADDR = {64'h40001FFF,64'h40000FFF,64'h0000000000000000,64'h0020FFFF};
    defparam axi4_bus0_inst.EXT_SLV_MAX_FRAGMENT_CNT = 2;
    cpu0 cpu0_inst (.dBusAxi_ar_payload_addr({cpu0_inst_AXI_M_DATA_interconnect_ARADDR}), 
         .dBusAxi_ar_payload_burst({cpu0_inst_AXI_M_DATA_interconnect_ARBURST}), 
         .dBusAxi_ar_payload_cache({cpu0_inst_AXI_M_DATA_interconnect_ARCACHE}), 
         .dBusAxi_ar_payload_id({cpu0_inst_AXI_M_DATA_interconnect_ARID}), 
         .dBusAxi_ar_payload_len({cpu0_inst_AXI_M_DATA_interconnect_ARLEN}), 
         .dBusAxi_ar_payload_prot({cpu0_inst_AXI_M_DATA_interconnect_ARPROT}), 
         .dBusAxi_ar_payload_qos({cpu0_inst_AXI_M_DATA_interconnect_ARQOS}), 
         .dBusAxi_ar_payload_region({cpu0_inst_AXI_M_DATA_interconnect_ARREGION}), 
         .dBusAxi_ar_payload_size({cpu0_inst_AXI_M_DATA_interconnect_ARSIZE}), 
         .dBusAxi_aw_payload_addr({cpu0_inst_AXI_M_DATA_interconnect_AWADDR}), 
         .dBusAxi_aw_payload_burst({cpu0_inst_AXI_M_DATA_interconnect_AWBURST}), 
         .dBusAxi_aw_payload_cache({cpu0_inst_AXI_M_DATA_interconnect_AWCACHE}), 
         .dBusAxi_aw_payload_id({cpu0_inst_AXI_M_DATA_interconnect_AWID}), 
         .dBusAxi_aw_payload_len({cpu0_inst_AXI_M_DATA_interconnect_AWLEN}), 
         .dBusAxi_aw_payload_prot({cpu0_inst_AXI_M_DATA_interconnect_AWPROT}), 
         .dBusAxi_aw_payload_qos({cpu0_inst_AXI_M_DATA_interconnect_AWQOS}), 
         .dBusAxi_aw_payload_region({cpu0_inst_AXI_M_DATA_interconnect_AWREGION}), 
         .dBusAxi_aw_payload_size({cpu0_inst_AXI_M_DATA_interconnect_AWSIZE}), 
         .dBusAxi_b_payload_id({cpu0_inst_AXI_M_DATA_interconnect_BID}), .dBusAxi_b_payload_resp({cpu0_inst_AXI_M_DATA_interconnect_BRESP}), 
         .dBusAxi_r_payload_data({cpu0_inst_AXI_M_DATA_interconnect_RDATA}), 
         .dBusAxi_r_payload_id({cpu0_inst_AXI_M_DATA_interconnect_RID}), .dBusAxi_r_payload_resp({cpu0_inst_AXI_M_DATA_interconnect_RRESP}), 
         .dBusAxi_w_payload_data({cpu0_inst_AXI_M_DATA_interconnect_WDATA}), 
         .dBusAxi_w_payload_strb({cpu0_inst_AXI_M_DATA_interconnect_WSTRB}), 
         .dbus_cmd_payload_address({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_address}), 
         .dbus_cmd_payload_data({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_data}), 
         .dbus_cmd_payload_mask({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_mask}), 
         .dbus_cmd_payload_size({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_size}), 
         .dbus_inv_payload_fragment_address({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_payload_fragment_address}), 
         .dbus_rsp_payload_data({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_data}), 
         .iBusAxi_ar_payload_addr({cpu0_inst_AXI_M_INSTR_interconnect_ARADDR}), 
         .iBusAxi_ar_payload_burst({cpu0_inst_AXI_M_INSTR_interconnect_ARBURST}), 
         .iBusAxi_ar_payload_cache({cpu0_inst_AXI_M_INSTR_interconnect_ARCACHE}), 
         .iBusAxi_ar_payload_id({cpu0_inst_AXI_M_INSTR_interconnect_ARID}), 
         .iBusAxi_ar_payload_len({cpu0_inst_AXI_M_INSTR_interconnect_ARLEN}), 
         .iBusAxi_ar_payload_prot({cpu0_inst_AXI_M_INSTR_interconnect_ARPROT}), 
         .iBusAxi_ar_payload_qos({cpu0_inst_AXI_M_INSTR_interconnect_ARQOS}), 
         .iBusAxi_ar_payload_region({cpu0_inst_AXI_M_INSTR_interconnect_ARREGION}), 
         .iBusAxi_ar_payload_size({cpu0_inst_AXI_M_INSTR_interconnect_ARSIZE}), 
         .iBusAxi_aw_payload_addr({cpu0_inst_AXI_M_INSTR_interconnect_AWADDR}), 
         .iBusAxi_aw_payload_burst({cpu0_inst_AXI_M_INSTR_interconnect_AWBURST}), 
         .iBusAxi_aw_payload_cache({cpu0_inst_AXI_M_INSTR_interconnect_AWCACHE}), 
         .iBusAxi_aw_payload_id({cpu0_inst_AXI_M_INSTR_interconnect_AWID}), 
         .iBusAxi_aw_payload_len({cpu0_inst_AXI_M_INSTR_interconnect_AWLEN}), 
         .iBusAxi_aw_payload_prot({cpu0_inst_AXI_M_INSTR_interconnect_AWPROT}), 
         .iBusAxi_aw_payload_qos({cpu0_inst_AXI_M_INSTR_interconnect_AWQOS}), 
         .iBusAxi_aw_payload_region({cpu0_inst_AXI_M_INSTR_interconnect_AWREGION}), 
         .iBusAxi_aw_payload_size({cpu0_inst_AXI_M_INSTR_interconnect_AWSIZE}), 
         .iBusAxi_b_payload_id({cpu0_inst_AXI_M_INSTR_interconnect_BID}), 
         .iBusAxi_b_payload_resp({cpu0_inst_AXI_M_INSTR_interconnect_BRESP}), 
         .iBusAxi_r_payload_data({cpu0_inst_AXI_M_INSTR_interconnect_RDATA}), 
         .iBusAxi_r_payload_id({cpu0_inst_AXI_M_INSTR_interconnect_RID}), 
         .iBusAxi_r_payload_resp({cpu0_inst_AXI_M_INSTR_interconnect_RRESP}), 
         .iBusAxi_w_payload_data({cpu0_inst_AXI_M_INSTR_interconnect_WDATA}), 
         .iBusAxi_w_payload_strb({cpu0_inst_AXI_M_INSTR_interconnect_WSTRB}), 
         .ibus_cmd_payload_address({cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_address}), 
         .ibus_cmd_payload_data({cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_data}), 
         .ibus_cmd_payload_mask({cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_mask}), 
         .ibus_cmd_payload_size({cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_size}), 
         .ibus_rsp_payload_data({cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_payload_data}), 
         .clk_realtime_i(osc0_inst_lf_clk_out_o_net), .clk_system_i(pll0_inst_clkop_o_net), 
         .dBusAxi_ar_payload_lock(cpu0_inst_AXI_M_DATA_interconnect_ARLOCK), 
         .dBusAxi_ar_ready(cpu0_inst_AXI_M_DATA_interconnect_ARREADY), .dBusAxi_ar_valid(cpu0_inst_AXI_M_DATA_interconnect_ARVALID), 
         .dBusAxi_aw_payload_lock(cpu0_inst_AXI_M_DATA_interconnect_AWLOCK), 
         .dBusAxi_aw_ready(cpu0_inst_AXI_M_DATA_interconnect_AWREADY), .dBusAxi_aw_valid(cpu0_inst_AXI_M_DATA_interconnect_AWVALID), 
         .dBusAxi_b_ready(cpu0_inst_AXI_M_DATA_interconnect_BREADY), .dBusAxi_b_valid(cpu0_inst_AXI_M_DATA_interconnect_BVALID), 
         .dBusAxi_r_payload_last(cpu0_inst_AXI_M_DATA_interconnect_RLAST), 
         .dBusAxi_r_ready(cpu0_inst_AXI_M_DATA_interconnect_RREADY), .dBusAxi_r_valid(cpu0_inst_AXI_M_DATA_interconnect_RVALID), 
         .dBusAxi_w_payload_last(cpu0_inst_AXI_M_DATA_interconnect_WLAST), 
         .dBusAxi_w_ready(cpu0_inst_AXI_M_DATA_interconnect_WREADY), .dBusAxi_w_valid(cpu0_inst_AXI_M_DATA_interconnect_WVALID), 
         .dbus_ack_payload_fragment_hit(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_payload_fragment_hit), 
         .dbus_ack_payload_last(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_payload_last), 
         .dbus_ack_ready(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_ready), 
         .dbus_ack_valid(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_valid), 
         .dbus_cmd_payload_exclusive(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_exclusive), 
         .dbus_cmd_payload_last(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_last), 
         .dbus_cmd_payload_uncached(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_uncached), 
         .dbus_cmd_payload_wr(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_wr), 
         .dbus_cmd_ready(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_ready), 
         .dbus_cmd_valid(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_valid), 
         .dbus_inv_payload_fragment_enable(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_payload_fragment_enable), 
         .dbus_inv_payload_last(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_payload_last), 
         .dbus_inv_ready(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_ready), 
         .dbus_inv_valid(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_valid), 
         .dbus_rsp_payload_error(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_error), 
         .dbus_rsp_payload_exclusive(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_exclusive), 
         .dbus_rsp_payload_last(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_last), 
         .dbus_rsp_valid(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_valid), 
         .iBusAxi_ar_payload_lock(cpu0_inst_AXI_M_INSTR_interconnect_ARLOCK), 
         .iBusAxi_ar_ready(cpu0_inst_AXI_M_INSTR_interconnect_ARREADY), .iBusAxi_ar_valid(cpu0_inst_AXI_M_INSTR_interconnect_ARVALID), 
         .iBusAxi_aw_payload_lock(cpu0_inst_AXI_M_INSTR_interconnect_AWLOCK), 
         .iBusAxi_aw_ready(cpu0_inst_AXI_M_INSTR_interconnect_AWREADY), .iBusAxi_aw_valid(cpu0_inst_AXI_M_INSTR_interconnect_AWVALID), 
         .iBusAxi_b_ready(cpu0_inst_AXI_M_INSTR_interconnect_BREADY), .iBusAxi_b_valid(cpu0_inst_AXI_M_INSTR_interconnect_BVALID), 
         .iBusAxi_r_payload_last(cpu0_inst_AXI_M_INSTR_interconnect_RLAST), 
         .iBusAxi_r_ready(cpu0_inst_AXI_M_INSTR_interconnect_RREADY), .iBusAxi_r_valid(cpu0_inst_AXI_M_INSTR_interconnect_RVALID), 
         .iBusAxi_w_payload_last(cpu0_inst_AXI_M_INSTR_interconnect_WLAST), 
         .iBusAxi_w_ready(cpu0_inst_AXI_M_INSTR_interconnect_WREADY), .iBusAxi_w_valid(cpu0_inst_AXI_M_INSTR_interconnect_WVALID), 
         .ibus_cmd_payload_last(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_last), 
         .ibus_cmd_payload_uncached(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_uncached), 
         .ibus_cmd_payload_wr(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_wr), 
         .ibus_cmd_ready(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_ready), 
         .ibus_cmd_valid(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_valid), 
         .ibus_rsp_payload_error(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_payload_error), 
         .ibus_rsp_payload_last(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_payload_last), 
         .ibus_rsp_valid(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_valid), 
         .irq2_i(emmc0_inst_INTR_interconnect_IRQ), .irq3_i(uart0_inst_INT_M0_interconnect_IRQ), 
         .rstn_i(equation_module_inst_O_net), .system_resetn_o(cpu0_inst_system_resetn_o_net));
    defparam cpu0_inst.AXI_DATA_BASE_ADDR = 32'h200000;
    defparam cpu0_inst.DCACHE_ENABLE = 1;
    defparam cpu0_inst.ICACHE_ENABLE = 1;
    defparam cpu0_inst.TCM_BASE_ADDR = 32'h0;
    defparam cpu0_inst.TCM_ENABLE = 1;
    emmc0 emmc0_inst (.emmc_dat_io({emmc_dat_io}), .m_axi4_awid_o({emmc0_inst_AXI4_M0_interconnect_AWID}), 
          .m_axi4_awaddr_o({emmc0_inst_AXI4_M0_interconnect_AWADDR}), .m_axi4_awlen_o({emmc0_inst_AXI4_M0_interconnect_AWLEN}), 
          .m_axi4_awsize_o({emmc0_inst_AXI4_M0_interconnect_AWSIZE}), .m_axi4_awburst_o({emmc0_inst_AXI4_M0_interconnect_AWBURST}), 
          .m_axi4_awprot_o({emmc0_inst_AXI4_M0_interconnect_AWPROT}), .m_axi4_wdata_o({emmc0_inst_AXI4_M0_interconnect_WDATA}), 
          .m_axi4_wstrb_o({emmc0_inst_AXI4_M0_interconnect_WSTRB}), .m_axi4_bid_i({emmc0_inst_AXI4_M0_interconnect_BID}), 
          .m_axi4_bresp_i({emmc0_inst_AXI4_M0_interconnect_BRESP}), .m_axi4_arid_o({emmc0_inst_AXI4_M0_interconnect_ARID}), 
          .m_axi4_araddr_o({emmc0_inst_AXI4_M0_interconnect_ARADDR}), .m_axi4_arlen_o({emmc0_inst_AXI4_M0_interconnect_ARLEN}), 
          .m_axi4_arsize_o({emmc0_inst_AXI4_M0_interconnect_ARSIZE}), .m_axi4_arburst_o({emmc0_inst_AXI4_M0_interconnect_ARBURST}), 
          .m_axi4_arprot_o({emmc0_inst_AXI4_M0_interconnect_ARPROT}), .m_axi4_rid_i({emmc0_inst_AXI4_M0_interconnect_RID}), 
          .m_axi4_rdata_i({emmc0_inst_AXI4_M0_interconnect_RDATA}), .m_axi4_rresp_i({emmc0_inst_AXI4_M0_interconnect_RRESP}), 
          .s_apb_paddr_i({apb_int0_inst_APB_M00_interconnect_PADDR}), .s_apb_pwdata_i({apb_int0_inst_APB_M00_interconnect_PWDATA}), 
          .s_apb_prdata_o({apb_int0_inst_APB_M00_interconnect_PRDATA}), .rst_n_i(cpu0_inst_system_resetn_o_net), 
          .clk_i(pll0_inst_clkop_o_net), .emmc_clk_o(emmc_clk_o), .emmc_cmd_io(emmc_cmd_io), 
          .emmc_rst_n_o(emmc_rst_n_o), .int_o(emmc0_inst_INTR_interconnect_IRQ), 
          .m_axi4_awready_i(emmc0_inst_AXI4_M0_interconnect_AWREADY), .m_axi4_awvalid_o(emmc0_inst_AXI4_M0_interconnect_AWVALID), 
          .m_axi4_wready_i(emmc0_inst_AXI4_M0_interconnect_WREADY), .m_axi4_wvalid_o(emmc0_inst_AXI4_M0_interconnect_WVALID), 
          .m_axi4_wlast_o(emmc0_inst_AXI4_M0_interconnect_WLAST), .m_axi4_bready_o(emmc0_inst_AXI4_M0_interconnect_BREADY), 
          .m_axi4_bvalid_i(emmc0_inst_AXI4_M0_interconnect_BVALID), .m_axi4_arready_i(emmc0_inst_AXI4_M0_interconnect_ARREADY), 
          .m_axi4_arvalid_o(emmc0_inst_AXI4_M0_interconnect_ARVALID), .m_axi4_rvalid_i(emmc0_inst_AXI4_M0_interconnect_RVALID), 
          .m_axi4_rready_o(emmc0_inst_AXI4_M0_interconnect_RREADY), .m_axi4_rlast_i(emmc0_inst_AXI4_M0_interconnect_RLAST), 
          .s_apb_penable_i(apb_int0_inst_APB_M00_interconnect_PENABLE), .s_apb_psel_i(apb_int0_inst_APB_M00_interconnect_PSELx), 
          .s_apb_pwrite_i(apb_int0_inst_APB_M00_interconnect_PWRITE), .s_apb_pready_o(apb_int0_inst_APB_M00_interconnect_PREADY), 
          .s_apb_pslverr_o(apb_int0_inst_APB_M00_interconnect_PSLVERR));
    osc0 osc0_inst (.hf_clk_out_o(osc0_inst_hf_clk_out_o_net), .hf_out_en_i(1'b1), 
         .lf_clk_out_o(osc0_inst_lf_clk_out_o_net));
    pll0 pll0_inst (.clki_i(osc0_inst_hf_clk_out_o_net), .clkop_o(pll0_inst_clkop_o_net), 
         .lock_o(pll0_inst_lock_o_net), .rstn_i(rstn_i));
    sysmem0 sysmem0_inst (.axi_s0_araddr_i({cpu0_inst_AXI_M_INSTR_interconnect_ARADDR}), 
            .axi_s0_arburst_i({cpu0_inst_AXI_M_INSTR_interconnect_ARBURST}), 
            .axi_s0_arcache_i({cpu0_inst_AXI_M_INSTR_interconnect_ARCACHE}), 
            .axi_s0_arid_i({Open_0, cpu0_inst_AXI_M_INSTR_interconnect_ARID}), 
            .axi_s0_arlen_i({cpu0_inst_AXI_M_INSTR_interconnect_ARLEN}), .axi_s0_arprot_i({cpu0_inst_AXI_M_INSTR_interconnect_ARPROT}), 
            .axi_s0_arqos_i({cpu0_inst_AXI_M_INSTR_interconnect_ARQOS}), .axi_s0_arregion_i({cpu0_inst_AXI_M_INSTR_interconnect_ARREGION}), 
            .axi_s0_arsize_i({cpu0_inst_AXI_M_INSTR_interconnect_ARSIZE}), 
            .axi_s0_awaddr_i({cpu0_inst_AXI_M_INSTR_interconnect_AWADDR}), 
            .axi_s0_awburst_i({cpu0_inst_AXI_M_INSTR_interconnect_AWBURST}), 
            .axi_s0_awcache_i({cpu0_inst_AXI_M_INSTR_interconnect_AWCACHE}), 
            .axi_s0_awid_i({Open_1, cpu0_inst_AXI_M_INSTR_interconnect_AWID}), 
            .axi_s0_awlen_i({cpu0_inst_AXI_M_INSTR_interconnect_AWLEN}), .axi_s0_awprot_i({cpu0_inst_AXI_M_INSTR_interconnect_AWPROT}), 
            .axi_s0_awqos_i({cpu0_inst_AXI_M_INSTR_interconnect_AWQOS}), .axi_s0_awregion_i({cpu0_inst_AXI_M_INSTR_interconnect_AWREGION}), 
            .axi_s0_awsize_i({cpu0_inst_AXI_M_INSTR_interconnect_AWSIZE}), 
            .axi_s0_bid_o({Open_2, cpu0_inst_AXI_M_INSTR_interconnect_BID}), 
            .axi_s0_bresp_o({cpu0_inst_AXI_M_INSTR_interconnect_BRESP}), .axi_s0_rdata_o({cpu0_inst_AXI_M_INSTR_interconnect_RDATA}), 
            .axi_s0_rid_o({Open_3, cpu0_inst_AXI_M_INSTR_interconnect_RID}), 
            .axi_s0_rresp_o({cpu0_inst_AXI_M_INSTR_interconnect_RRESP}), .axi_s0_wdata_i({cpu0_inst_AXI_M_INSTR_interconnect_WDATA}), 
            .axi_s0_wstrb_i({cpu0_inst_AXI_M_INSTR_interconnect_WSTRB}), .axi_s1_araddr_i({axi4_bus0_inst_AXI_M00_interconnect_ARADDR}), 
            .axi_s1_arburst_i({axi4_bus0_inst_AXI_M00_interconnect_ARBURST}), 
            .axi_s1_arcache_i({axi4_bus0_inst_AXI_M00_interconnect_ARCACHE}), 
            .axi_s1_arid_i({axi4_bus0_inst_AXI_M00_interconnect_ARID}), .axi_s1_arlen_i({axi4_bus0_inst_AXI_M00_interconnect_ARLEN}), 
            .axi_s1_arprot_i({axi4_bus0_inst_AXI_M00_interconnect_ARPROT}), 
            .axi_s1_arqos_i({axi4_bus0_inst_AXI_M00_interconnect_ARQOS}), 
            .axi_s1_arregion_i({axi4_bus0_inst_AXI_M00_interconnect_ARREGION}), 
            .axi_s1_arsize_i({axi4_bus0_inst_AXI_M00_interconnect_ARSIZE}), 
            .axi_s1_awaddr_i({axi4_bus0_inst_AXI_M00_interconnect_AWADDR}), 
            .axi_s1_awburst_i({axi4_bus0_inst_AXI_M00_interconnect_AWBURST}), 
            .axi_s1_awcache_i({axi4_bus0_inst_AXI_M00_interconnect_AWCACHE}), 
            .axi_s1_awid_i({axi4_bus0_inst_AXI_M00_interconnect_AWID}), .axi_s1_awlen_i({axi4_bus0_inst_AXI_M00_interconnect_AWLEN}), 
            .axi_s1_awprot_i({axi4_bus0_inst_AXI_M00_interconnect_AWPROT}), 
            .axi_s1_awqos_i({axi4_bus0_inst_AXI_M00_interconnect_AWQOS}), 
            .axi_s1_awregion_i({axi4_bus0_inst_AXI_M00_interconnect_AWREGION}), 
            .axi_s1_awsize_i({axi4_bus0_inst_AXI_M00_interconnect_AWSIZE}), 
            .axi_s1_bid_o({axi4_bus0_inst_AXI_M00_interconnect_BID}), .axi_s1_bresp_o({axi4_bus0_inst_AXI_M00_interconnect_BRESP}), 
            .axi_s1_rdata_o({axi4_bus0_inst_AXI_M00_interconnect_RDATA}), 
            .axi_s1_rid_o({axi4_bus0_inst_AXI_M00_interconnect_RID}), .axi_s1_rresp_o({axi4_bus0_inst_AXI_M00_interconnect_RRESP}), 
            .axi_s1_wdata_i({axi4_bus0_inst_AXI_M00_interconnect_WDATA}), 
            .axi_s1_wstrb_i({axi4_bus0_inst_AXI_M00_interconnect_WSTRB}), 
            .axi_aclk_i(pll0_inst_clkop_o_net), .axi_resetn_i(cpu0_inst_system_resetn_o_net), 
            .axi_s0_arlock_i(cpu0_inst_AXI_M_INSTR_interconnect_ARLOCK), .axi_s0_arready_o(cpu0_inst_AXI_M_INSTR_interconnect_ARREADY), 
            .axi_s0_arvalid_i(cpu0_inst_AXI_M_INSTR_interconnect_ARVALID), 
            .axi_s0_awlock_i(cpu0_inst_AXI_M_INSTR_interconnect_AWLOCK), .axi_s0_awready_o(cpu0_inst_AXI_M_INSTR_interconnect_AWREADY), 
            .axi_s0_awvalid_i(cpu0_inst_AXI_M_INSTR_interconnect_AWVALID), 
            .axi_s0_bready_i(cpu0_inst_AXI_M_INSTR_interconnect_BREADY), .axi_s0_bvalid_o(cpu0_inst_AXI_M_INSTR_interconnect_BVALID), 
            .axi_s0_rlast_o(cpu0_inst_AXI_M_INSTR_interconnect_RLAST), .axi_s0_rready_i(cpu0_inst_AXI_M_INSTR_interconnect_RREADY), 
            .axi_s0_rvalid_o(cpu0_inst_AXI_M_INSTR_interconnect_RVALID), .axi_s0_wlast_i(cpu0_inst_AXI_M_INSTR_interconnect_WLAST), 
            .axi_s0_wready_o(cpu0_inst_AXI_M_INSTR_interconnect_WREADY), .axi_s0_wvalid_i(cpu0_inst_AXI_M_INSTR_interconnect_WVALID), 
            .axi_s1_arlock_i(axi4_bus0_inst_AXI_M00_interconnect_ARLOCK), 
            .axi_s1_arready_o(axi4_bus0_inst_AXI_M00_interconnect_ARREADY), 
            .axi_s1_arvalid_i(axi4_bus0_inst_AXI_M00_interconnect_ARVALID), 
            .axi_s1_awlock_i(axi4_bus0_inst_AXI_M00_interconnect_AWLOCK), 
            .axi_s1_awready_o(axi4_bus0_inst_AXI_M00_interconnect_AWREADY), 
            .axi_s1_awvalid_i(axi4_bus0_inst_AXI_M00_interconnect_AWVALID), 
            .axi_s1_bready_i(axi4_bus0_inst_AXI_M00_interconnect_BREADY), 
            .axi_s1_bvalid_o(axi4_bus0_inst_AXI_M00_interconnect_BVALID), 
            .axi_s1_rlast_o(axi4_bus0_inst_AXI_M00_interconnect_RLAST), .axi_s1_rready_i(axi4_bus0_inst_AXI_M00_interconnect_RREADY), 
            .axi_s1_rvalid_o(axi4_bus0_inst_AXI_M00_interconnect_RVALID), 
            .axi_s1_wlast_i(axi4_bus0_inst_AXI_M00_interconnect_WLAST), .axi_s1_wready_o(axi4_bus0_inst_AXI_M00_interconnect_WREADY), 
            .axi_s1_wvalid_i(axi4_bus0_inst_AXI_M00_interconnect_WVALID));
    defparam sysmem0_inst.MEM_ID = "sysmem0";
    tcm0 tcm0_inst (.dbus_cmd_payload_address({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_address}), 
         .dbus_cmd_payload_data({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_data}), 
         .dbus_cmd_payload_mask({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_mask}), 
         .dbus_cmd_payload_size({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_size}), 
         .dbus_inv_payload_fragment_address({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_payload_fragment_address}), 
         .dbus_rsp_payload_data({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_data}), 
         .ibus_cmd_payload_address({cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_address}), 
         .ibus_cmd_payload_data({cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_data}), 
         .ibus_cmd_payload_mask({cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_mask}), 
         .ibus_cmd_payload_size({cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_size}), 
         .ibus_rsp_payload_data({cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_payload_data}), 
         .dbus_ack_payload_fragment_hit(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_payload_fragment_hit), 
         .dbus_ack_payload_last(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_payload_last), 
         .dbus_ack_ready(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_ready), 
         .dbus_ack_valid(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_valid), 
         .dbus_cmd_payload_exclusive(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_exclusive), 
         .dbus_cmd_payload_last(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_last), 
         .dbus_cmd_payload_uncached(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_uncached), 
         .dbus_cmd_payload_wr(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_wr), 
         .dbus_cmd_ready(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_ready), 
         .dbus_cmd_valid(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_valid), 
         .dbus_inv_payload_fragment_enable(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_payload_fragment_enable), 
         .dbus_inv_payload_last(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_payload_last), 
         .dbus_inv_ready(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_ready), 
         .dbus_inv_valid(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_valid), 
         .dbus_rsp_payload_error(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_error), 
         .dbus_rsp_payload_exclusive(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_exclusive), 
         .dbus_rsp_payload_last(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_last), 
         .dbus_rsp_valid(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_valid), 
         .ibus_cmd_payload_last(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_last), 
         .ibus_cmd_payload_uncached(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_uncached), 
         .ibus_cmd_payload_wr(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_wr), 
         .ibus_cmd_ready(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_ready), 
         .ibus_cmd_valid(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_valid), 
         .ibus_rsp_payload_error(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_payload_error), 
         .ibus_rsp_payload_last(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_payload_last), 
         .ibus_rsp_valid(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_valid), 
         .sys_clk(pll0_inst_clkop_o_net), .sys_rst_n(cpu0_inst_system_resetn_o_net));
    defparam tcm0_inst.MEM_ID = "1.5.2";
    uart0 uart0_inst (.apb_paddr_i({apb_int0_inst_APB_M01_interconnect_PADDR[5:0]}), 
          .apb_prdata_o({apb_int0_inst_APB_M01_interconnect_PRDATA}), .apb_pwdata_i({apb_int0_inst_APB_M01_interconnect_PWDATA}), 
          .apb_penable_i(apb_int0_inst_APB_M01_interconnect_PENABLE), .apb_pready_o(apb_int0_inst_APB_M01_interconnect_PREADY), 
          .apb_psel_i(apb_int0_inst_APB_M01_interconnect_PSELx), .apb_pslverr_o(apb_int0_inst_APB_M01_interconnect_PSLVERR), 
          .apb_pwrite_i(apb_int0_inst_APB_M01_interconnect_PWRITE), .clk_i(pll0_inst_clkop_o_net), 
          .int_o(uart0_inst_INT_M0_interconnect_IRQ), .rst_n_i(cpu0_inst_system_resetn_o_net), 
          .rxd_i(uart0_rxd_i), .txd_o(uart0_txd_o));
    
endmodule

